gooddata/gooddata-react-components

src/components/core/PureTable.tsx
src/components/core/tests/PureTable.spec.tsx

In KD the date filter in right panel was enabled even if the visualization had an metric date filter but execution ended up with no data

RELATED: BB-631 Fix visualization date filter enabled 

---

__mocks__/fixtures.ts
src/helpers/popHelper.ts
src/helpers/tests/popHelper.spec.ts

The title of the derived measure must be created from the current name of the master measure. 
* When a **master measure is not renamed** then the derived measure name must be based on the **master measure title**. 
* When a **master measure is renamed** the derived measure name must be based on **master measure alias**.

RELATED: BB-703 Base the derived measure title on the current master measure name

---

package.json
src/execution/fixtures/ExecuteAfm.fixtures.ts
src/helpers/errorHandlers.ts
src/helpers/tests/errorHandlers.spec.ts
yarn.lock

`5.2.0-ocetnik-doc-gd-js-paging-2018-07-03T12-13-59-398Z`

RELATED: RAIL-900 Upgrade gooddata-js, mock-js and convert other than apiResponse errors

---

src/components/visualizations/chart/chartOptionsBuilder.ts

Caused by 05a77cc4 refactor which revealed that we still used
smaller limits (DEFAULT_CATEGORIES_LIMIT=365) when rendering scatter.

RELATED: ONE-3265 Turn off turbo threshold for scatter series

---

__mocks__/fixtures.ts
src/components/uri/Visualization.tsx
src/components/visualizations/chart/chartOptionsBuilder.ts
src/components/visualizations/chart/test/chartOptionsBuilder.spec.ts
src/helpers/overTimeComparisonHelper.ts
src/helpers/tests/overTimeComparisonHelper.spec.ts
src/index.ts
stories/test_data/bar_chart_with_paged_legend.ts
stories/test_data/test_config.ts

PoP stays in context of measure definition where it is still valid part to backend API

RELATED: BB-638 Refactor PoP to Over Time Comparison

---

package.json

The version was overwritten by the wrong release via CI job (the `master` branch was specified instead of intended `next-6.0.0`).

CONFIG: Revert wrongly overwritten version

---

src/components/afm/Table.tsx
src/components/afm/tests/Table.spec.tsx
src/components/afm/tests/utils/dummyFixture.ts

`6.0.0-ocetnik-doc-afm-measure-empty-array-2018-10-18T10-48-02-035Z`

BUGFIX: RAIL-1180 AFM Table Component generates resultSpec without measureGroup when afm.measures=[]

---

package.json
src/factory/DerivedMeasureTitleSuffixFactory.ts
src/factory/tests/DerivedMeasureTitleSuffixFactory.spec.ts
src/helpers/measureTitleHelper.ts
src/index.ts
src/interfaces/OverTimeComparison.ts

The factory should not be dependent on the measure definition (similarly to the arithmetic measure title factory). This way the whole measure definition does not need to be stored in the decorated bucket item in Analytical Designer. For this purpose the OverTimeComparison interface was moved from gdc-app-components into the gooddata-react-component repo.

RELATED: BB-1159 Refactor of the derived measures title factory

---

CHANGELOG.md
package.json
yarn.lock

The logic of the date filter merging is moved from frontend to the backend as the backend needs to know which filters were global and which local (measure filters) in order to construct correct MAQL queries.
In addition to that, the backend REST API is versioned now. The original API version 1 still expects the date filters to be merged by the frontend (in order for GoodData.UI SDK to be backward compatible for at least a year) while API version 2  and newer expects the filters in the original buckets as they were set by the user.
When the backend returns X-GDC-DEPRECATED response header, the frontend client will output warning into the browser's console. The header is returned in the case when value sent in the X-GDC-VERSION does not identify the latest REST API version deployed on the …

RELATED: BB-1203 Migrate date filters merging from web client to backend

---

src/translations/es-ES.json
src/translations/ja-JP.json

Space in translation
```
"measure.title.suffix.previous_period": " 期前"
```
is INTENDED

RELATED: BB-1265, RELATED: BB-1268 Fix translations

---

examples/src/components/utils/Header.jsx

Adds a link to the BackendInfo bar pointing to the file containing the ID's we use.

RELATED: RAIL-1164 add 'Data Used' link to BackendInfo in Header

---

examples/src/components/ArithmeticMeasureChangeExample.jsx
examples/src/components/ArithmeticMeasureDrillingExample.jsx
examples/src/components/ArithmeticMeasureMultiplicationExample.jsx
examples/src/components/ArithmeticMeasureRatioExample.jsx
examples/src/components/ArithmeticMeasureSumExample.jsx
examples/src/components/DrillWithExternalDataExample.jsx
examples/src/components/PivotTableDrillExample.jsx
examples/src/components/PivotTableDynamicExample.jsx
examples/src/routes/ArithmeticMeasure.jsx
examples/src/routes/_list.js
examples/src/utils/fixtures.js

Add new Arithmetic Measures page to the SDK public
examples project.
Table is used for all samples as it seems to be the
most straightforward visualization. Also, all arithmetic
operations are shown, incl. derived metrics and
arithmetic measure drilling.
New Drilling API from BB-1127 was used and other drilling
examples were updated as well.

RELATED: BB-1116 Add Arithmetic Measures examples

---

package.json
yarn.lock

mock-js @ 1.14 was incorrectly sorting data; using string comparison instead of number comparison. this has potential to result in semantically bad mocked data (lexi sorting.. "9" > "100000").

RELATED: FET-213 New version of mock-js with corrected sorting behavior

---

src/components/core/PivotTable.tsx
src/components/visualizations/chart/ChartTransformation.tsx
src/components/visualizations/chart/chartOptionsBuilder.ts
src/components/visualizations/chart/colorFactory.ts
src/components/visualizations/chart/test/chartOptionsBuilder.spec.ts
src/components/visualizations/chart/test/colorFactory.spec.ts
src/components/visualizations/chart/test/helper.ts
src/components/visualizations/headline/utils/HeadlineTransformationUtils.ts
src/components/visualizations/table/ResponsiveTable.tsx
src/components/visualizations/table/TableTransformation.tsx
src/components/visualizations/table/TableVisualization.tsx
src/components/visualizations/table/test/ResponsiveTable.spec.tsx
src/components/visualizations/table/test/TableVisualization.spec.tsx
src/components/visualizations/utils/color.ts
src/components/visualizations/utils/test/color.spec.ts
src/factory/HeaderPredicateFactory.ts
src/factory/tests/HeaderPredicateFactory.spec.ts
src/factory/tests/mocks.ts
src/helpers/headerPredicate.ts
src/helpers/tests/headerPredicate.spec.ts
src/interfaces/HeaderPredicate.ts
stories/internal/Visualization.tsx

This PR adds ability to work with execution response in header predicates. Execution response is needed to fully support drilling on AMs because only AFM is not enough to obtain information such identifier from measure headers.

RELATED: BB-1326 Pass executionResponse to header predicate calls

---

src/components/core/PivotTable.tsx

Makes sure the `gridApi` object has been set before calling its methods.

TRIVIAL: add preventive null check to PivotTable

---

src/components/core/pivotTable/HeaderCell.tsx
src/components/core/pivotTable/tests/HeaderCell.spec.tsx

Adds sorting direction `s-` class to PivotTabel HeaderCell to facilitate testing

RELATED: RAIL-1137 add sorting direction s- class to HeaderCell

---

src/components/core/PivotTable.tsx
src/components/core/base/VisualizationLoadingHOC.tsx
src/components/core/base/test/VisualizationLoadingHOC.spec.tsx

**DO NOT MERGE**
The code within changes how sortItems are propagated. 
Before:
- Calculate & send sortItems with every request to getPage() ==> unnecessary cycles spent + repeated dispatch of sortItems 'broke' AD undo/redo
After:
- listen for ag-grid onSortChanged event
- then retrieve sort model from columns, via columnApi incoming in event payload
- calculate sortItems using sortModel & existing execution
- call onSortChange callback received on PivotTable props
- call pushData with properties: { sortItems }

BUGFIX: RAIL-1241 Push sorts only once, right after they have changed

---

CHANGELOG.md

Updated changelog according to https://confluence.intgdc.com/display/GDUI/6.2.0

TRIVIAL: Update changelog for 6.2.0 release

---

CHANGELOG.md
src/components/visualizations/chart/chartOptionsBuilder.ts
src/components/visualizations/chart/test/chartOptionsBuilder.spec.ts
src/components/visualizations/table/utils/dataTransformation.ts
src/components/visualizations/utils/drilldownEventing.ts
src/components/visualizations/utils/test/drilldownEventing.spec.tsx
src/constants/visualizationTypes.ts
src/interfaces/DrillEvents.ts

First volume of drill cleanup:
1. Marked old drillable intersection as `ILegacyDrillIntersection`. This legacy type will be replaced by `IDrillEventIntersectionElement` in next volume.
2. Added type `DrillEventContext` to some lines of code that was not been typed previously to easily search where we use such type.
3. Drill context was split into 2 interfaces `IDrillEventContextSingle` for classic context, `IDrillEventContextGroup` for group context (group is used when chart has more series drill-activated and user clicks on axis label - group event is fired - every point has own intersection).
4. Renamed property of HC helper object including interface`IHighchartsPointObject`- original was `drillContext`, correct is `drillIntersection`
5. Heatmap and Treemap now return value as strings …

RELATED: BB-1318 Drilling cleanup vol 1

---

src/components/visualizations/chart/highcharts/plugins/dualAxesLabelFormatter.ts
src/components/visualizations/chart/highcharts/plugins/test/dualAxesLabelFormatter.spec.ts

Handle exponential number case.
Convert `1e-5` to `0.00001` by using 'Number.toFixed()', while 'Number.toString()' converts it to unexpected `1e-5` as as-is.

SD-273: handle exponential number case

---

package.json
src/components/filters/AttributeFilter/AttributeDropdown.tsx
src/components/filters/AttributeFilter/AttributeElements.tsx
src/components/filters/AttributeFilter/AttributeFilter.tsx
src/components/filters/AttributeFilter/AttributeLoader.tsx
src/components/filters/AttributeFilter/tests/AttributeDropdown.spec.tsx
src/components/filters/AttributeFilter/tests/utils.ts
src/components/visualizations/chart/highcharts/getOptionalStackingConfiguration.ts
src/components/visualizations/chart/highcharts/plugins/linearTickPositions.ts
src/components/visualizations/chart/highcharts/plugins/test/getTickPositions.spec.ts
src/components/visualizations/chart/highcharts/plugins/zeroAlignYAxis.ts
src/components/visualizations/table/TableTransformation.tsx
src/components/visualizations/table/TableVisualization.tsx
src/components/visualizations/table/totals/TotalCell.tsx
src/execution/tests/Execute.spec.tsx
src/helpers/executionResultHelper.ts
src/helpers/visualizationType.ts
src/interfaces/Table.ts
yarn.lock

The Function types were replaced by concrete types where possible.
The places where correct type was impossible to determine were marked.
https://github.com/gooddata/gdc-app-components/pull/513
https://github.com/gooddata/gdc-dashboards/pull/1719 ✅
https://github.com/gooddata/gdc-analytical-designer/pull/2086 ✅

RELATED: FET-281 update tslint rules, fix issues

---

src/components/BarChart.tsx
src/components/ColumnChart.tsx
src/components/visualizations/chart/highcharts/getOptionalStackingConfiguration.ts
src/components/visualizations/chart/highcharts/test/getOptionalStackingConfiguration.spec.ts
src/helpers/optionalStacking/common.ts
src/helpers/optionalStacking/test/optionalStacking.spec.ts

---
AD: https://github.com/gooddata/gdc-analytical-designer/pull/2098
KD: https://github.com/gooddata/gdc-dashboards/pull/1740

RELATED: SD-311 SD-312 disable stacking config at high level when there is one measure

---

package.json
src/components/AreaChart.tsx
src/components/BarChart.tsx
src/components/BubbleChart.tsx
src/components/ColumnChart.tsx
src/components/ComboChart.tsx
src/components/DonutChart.tsx
src/components/FunnelChart.tsx
src/components/Headline.tsx
src/components/Heatmap.tsx
src/components/LineChart.tsx
src/components/PieChart.tsx
src/components/PivotTable.tsx
src/components/ScatterPlot.tsx
src/components/Table.tsx
src/components/Treemap.tsx
src/helpers/model/filters.ts
src/helpers/model/tests/filters.spec.ts
yarn.lock

- Changed input types for all visualization components; instead of using mix of VisualizationObject and AFM types, we now use unified VisualizationInput types; these eventually alias to effective types from VO or AFM
- The VisualizationInput types define filters as mix of date filters from VO and attribute filters from AFM; attribute filters from AFM allow to optionally indicate whether filter is a text filter or not; this change is backward compatible
- Updated filter helpers so that they allow creation of text filters

ONE-3610 Support for text filters

---

src/components/core/PivotTable.tsx
src/components/core/pivotTable/stickyGroupHandler.ts
src/components/core/pivotTable/tests/stickyGroupHandler.spec.ts
src/helpers/agGrid.ts
src/helpers/tests/agGrid.spec.ts
styles/scss/pivotTable.scss

Happens on table with only columns and rows but no measures. This should also fix disappearing sticky header when scrolling horizontally.

BUGFIX: BB-1463 Hide blank space on pivot table

---

package.json
src/helpers/model/measures.ts
src/helpers/model/tests/measures.spec.ts
src/helpers/tests/conversion.spec.ts
yarn.lock

Changes included in this PR complete the text filters story by supporting text filters in simple measure definitions (which can include attribute filters that can be textual). I did not catch this 'nuance' in my first PR 😞 
Majority of the work is done in gooddata-typings, where I overridden VisualizationInput.IMeasure definition with a mix of aliases to visualizaiton object measure definitions and custom simple measure definition which can accept filters in AFM format - same as with regular filters, these will be converted to ExecuteAFM type system and sent to backend in correct notation.

FEATURE: ONE-3610 Support text filters in simple measure

---

src/components/visualizations/chart/highcharts/customConfiguration.ts
src/components/visualizations/chart/highcharts/test/customConfiguration.spec.ts

- gdc-analytical-designer:  https://github.com/gooddata/gdc-analytical-designer/pull/2126
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/1790
- SD-359: https://jira.intgdc.com/browse/SD-359

BUGFIX: SD-359 escape both parent and child attributes

---

src/components/visualizations/chart/chartOptionsBuilder.ts
src/components/visualizations/chart/highcharts/customConfiguration.ts
src/components/visualizations/chart/test/chartOptionsBuilder.spec.ts
src/components/visualizations/chart/test/tooltip.spec.ts
src/components/visualizations/chart/tooltip.ts
src/helpers/tests/utils.spec.ts
src/helpers/utils.ts

PR for [SD-345](https://jira.intgdc.com/browse/SD-345)
---
- Show percent values in tooltip when stackMeasuresToPercent is true
- Pass percentage value into tooltip builder
- Add new function percentFormatter into utils helper
- Add Unit tests
---

BUGFIX: SD-345 - Show percent values when stackMeasuresToPercent is true

---

src/components/core/PivotTable.tsx
src/components/core/pivotTable/agGridApiWrapper.ts
src/components/core/pivotTable/stickyGroupHandler.ts
src/components/core/pivotTable/tests/agGridApiWrapper.spec.tsx
src/components/core/pivotTable/tests/stickyGroupHandler.spec.ts

We are no longer using official API method `setPinnedTopRowData` in order to set pivot table group sticky header content. We are managing the content manually now.
---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2152
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/1848
- BB-1479: …

FEATURE: BB-1479 pivot table grouping performance optimizations

---

src/components/visualizations/chart/chartOptionsBuilder.ts
src/components/visualizations/chart/test/chartOptionsBuilder.spec.ts
src/components/visualizations/chart/test/tooltip.spec.ts
src/components/visualizations/chart/tooltip.ts

PR for [SD-400](https://jira.intgdc.com/browse/SD-400)
- Fix tooltip content for dual axes chart
---
--- | ---
- gdc-app-components: https://github.com/gooddata/gdc-app-components/pull/545
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2186
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/1882

BUGFIX: SD-400 - Show tooltip percent while value of measure display number

---

src/components/visualizations/chart/chartOptions/extendedStackingChartOptions.ts
src/components/visualizations/chart/chartOptions/test/extendedStackingChartOptions.spec.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2209
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/1926

BUGFIX: SD-425 Different reports in case of loading NULL fact

---

src/helpers/agGrid.ts
src/helpers/tests/agGrid.spec.ts
src/interfaces/AGGrid.ts

--- | ---
- gdc-app-components: https://github.com/gooddata/gdc-app-components/pull/561
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2215
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/1940

RELATED: RAIL-1539 distinguish active row totals

---

CHANGELOG.md
src/components/visualizations/utils/drilldownEventing.ts
src/interfaces/Config.ts
src/interfaces/DrillEvents.ts

This PR fixes TS types incompatibility introduced as minor breaking changes.
1. Drilling typing is more strict https://github.com/gooddata/gooddata-react-components/commit/4e1a23e7
Fixed by simplifying drilling types so they look like the previous version.
2. Moved export of IRGBColor and other to another repo  and https://github.com/gooddata/gooddata-react-components/commit/31b9339d
Fixed by reexporting original types.

 BUGFIX: BB-1519 Make drilling types backward compatible,  RELATED: BB-1519 Reexport color types

---

src/components/uri/Visualization.tsx
src/helpers/MdObjectHelper.ts

BUGFIX: RAIL-1562 Pivot table which isn't applied filter can't render by Visualization component

---

src/components/visualizations/chart/highcharts/plugins/autohideLabels/autohideColumnLabels.ts
src/components/visualizations/chart/highcharts/plugins/autohideLabels/test/autohideColumnLabels.spec.ts
src/interfaces/Config.ts

---
--- | ---
- gdc-app-components: https://github.com/gooddata/gdc-app-components/pull/575
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2247
- gdc-dashboard: https://github.com/gooddata/gdc-dashboards/pull/1983

BUGFIX: SD-461 only check width when shapeArgs existed for hiding data label

---

src/components/visualizations/chart/chartOptionsBuilder.ts
src/components/visualizations/chart/highcharts/commonConfiguration.ts
src/components/visualizations/chart/highcharts/lineConfiguration.ts
src/components/visualizations/chart/test/chartOptionsBuilder.spec.ts

---
--- | ---
AD: https://client-demo.na.intgdc.com:50019/analyze/
- SD-441: https://jira.intgdc.com/browse/SD-441
- SD-442: https://jira.intgdc.com/browse/SD-442

BUGFIX: SD-441 fix tooltip is rendered off screen; SD-442 disable saturate others on hover for line chart

---

src/components/afm/tests/Heatmap.spec.tsx
src/components/visualizations/chart/chartOptionsBuilder.ts
src/components/visualizations/chart/test/chartOptionsBuilder.spec.ts

--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2255
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2001
- SD-480: https://jira.intgdc.com/browse/SD-480

BUGFIX: SD-480 fix showing tooltip for treemap

---

src/components/visualizations/chart/highcharts/comboConfiguration.ts
src/components/visualizations/chart/highcharts/test/comboConfiguration.spec.ts

--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2290
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2024
- SD-494: https://jira.intgdc.com/browse/SD-494

BUGFIX: SD-494 disable saturate other element on hover for combo line line

---

examples/test/PivotTableXss_test.js
src/components/core/pivotTable/agGridUtils.ts

--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2311
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2065

RELATED: RAIL-1623 handle XSS in the data itself

---

examples/src/components/HeadlineExportExample.jsx
examples/src/routes/Export.jsx
src/components/afm/DataSourceProvider.tsx
src/components/afm/Headline.ts
src/components/afm/tests/DataSourceProvider.spec.tsx
stories/internal/Export.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2305
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2064
- SD-518: https://jira.intgdc.com/browse/SD-518

BUGFIX: SD-518 Revert - Disable Headline exporting in SDK

---

src/components/visualizations/chart/chartOptionsBuilder.ts
src/components/visualizations/chart/highcharts/comboConfiguration.ts
src/components/visualizations/chart/highcharts/dataLabelsHelpers.ts
src/components/visualizations/chart/highcharts/test/comboConfiguration.spec.ts
src/helpers/mdObjBucketHelper.ts

--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2320
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2077
- SD-525: https://jira.intgdc.com/browse/SD-525
- SD-526: https://jira.intgdc.com/browse/SD-526

BUGFIX: SD-526 fix treemap with null data point; SD-525 fix disable saturation others series in combo

---

src/components/visualizations/utils/drilldownEventing.ts
src/components/visualizations/utils/test/drilldownEventing.spec.tsx

Related to the changes in PR: https://github.com/gooddata/gooddata-react-components/pull/1038
Should add new props (in drill down event) for combo chart only
---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2347
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2081

RELATED: SD-469 - Apply custom props for Combo chart only

---

src/components/core/PivotTable.tsx

Stop onMouseEvent during table column resize to prevent widget move in KD edit mode
---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2356
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2127
https://jira.intgdc.com/browse/ONE-3883

RELATED: ONE-3883 Stop onMouseDown propagation during column resizing

---

src/components/core/PivotTable.tsx

Different way of handler registration to work with DnD backend
---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2364
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2137
https://jira.intgdc.com/browse/ONE-3883

RELATED: ONE-3883 Better preventing of mouse down on resizer

---

src/internal/components/pluggableVisualizations/comboChart/PluggableComboChart.tsx
src/internal/constants/supportedProperties.ts
src/internal/interfaces/Visualization.ts
src/internal/utils/uiConfigHelpers/comboChartUiConfigHelper.ts
src/internal/utils/uiConfigHelpers/tests/comboChartUiConfigHelper.spec.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2367
- gdc-dashboards: TBD
- SD-556: https://jira.intgdc.com/browse/SD-556

BUGFIX: SD-556 move canStackInPercent to uiConfig

---

src/components/afm/DataSourceProvider.tsx
src/components/afm/tests/DataSourceProvider.spec.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2400
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2182
- ONE-3939: https://jira.intgdc.com/browse/ONE-3939

BUGFIX: ONE-3939 Prevent double execution with wrong dataSource

---

src/components/visualizations/Visualization.tsx
src/components/visualizations/chart/Chart.tsx
src/components/visualizations/chart/HighChartsRenderer.tsx
src/components/visualizations/chart/chartOptionsBuilder.ts
src/components/visualizations/chart/events/setupDrilldownToParentAttribute.ts
src/components/visualizations/chart/highcharts/commonConfiguration.ts
src/components/visualizations/chart/highcharts/dataLabelsHelpers.ts
src/components/visualizations/chart/highcharts/heatmapConfiguration.ts
src/components/visualizations/chart/highcharts/highchartsEntryPoint.ts
src/components/visualizations/chart/highcharts/plugins/adjustTickAmount.ts
src/components/visualizations/chart/highcharts/plugins/autohideLabels/autohideColumnLabels.ts
src/components/visualizations/chart/highcharts/plugins/autohideLabels/test/autohideColumnLabels.spec.ts
src/components/visualizations/chart/highcharts/plugins/renderBubbles.ts
src/components/visualizations/chart/highcharts/test/getOptionalStackingConfiguration.spec.ts
src/components/visualizations/chart/legend/legendBuilder.ts
src/components/visualizations/chart/test/Chart.spec.tsx
src/components/visualizations/chart/test/chartOptionsBuilder.spec.ts
src/components/visualizations/utils/drilldownEventing.ts
src/components/visualizations/utils/test/drilldownEventing.spec.tsx
src/constants/label.ts
src/interfaces/Config.ts
src/interfaces/DrillEvents.ts
src/interfaces/HighchartsExtend.ts

Explicitly import HCH typings wherever it is used
---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2424
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2213
- ONE-3970: https://jira.intgdc.com/browse/ONE-3970

BUGFIX: ONE-3970 Import typings from Highcharts where needed

---

src/components/simple/Kpi.tsx
src/components/simple/tests/Kpi.spec.tsx
src/execution/fixtures/ExecuteAfm.fixtures.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2434
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2217

BUGFIX: RAIL-1695 handle case when server returns [null] in Kpi

---

src/components/visualizations/chart/highcharts/customConfiguration.ts
src/components/visualizations/chart/highcharts/test/customConfiguration.spec.ts
src/components/visualizations/chart/test/highChartsCreators.spec.ts
src/components/visualizations/styles/charts.scss
src/components/visualizations/styles/tooltip.scss
src/interfaces/Config.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2480
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2288
- SD-632: https://jira.intgdc.com/browse/SD-632

BUGFIX: SD-632 use absolute position for tooltip

---

src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx
src/internal/utils/mdObjectHelper.ts
src/internal/utils/sort.ts
src/internal/utils/tests/mdObjectHelper.spec.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2488
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2297
- SD-583: https://jira.intgdc.com/browse/SD-583

BUGFIX: SD-583 sort stacked bar chart by total values

---

src/helpers/conversion.ts
src/helpers/tests/conversion.spec.ts

Use only filters from AFM conversion, without negative filter with empty selection
---
--- | ---
- gdc-analytical-designer:  https://github.com/gooddata/gooddata-react-components/pull/1181#issue-321576187
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2303
Example:
- ONE-4084: https://jira.intgdc.com/browse/ONE-4084

BUGFIX: ONE-4048 Remove negative filter with empty selection from AFM

---

package.json
src/components/filters/AttributeFilter/AttributeDropdown.tsx
src/components/filters/AttributeFilter/tests/AttributeDropdown.spec.tsx
src/components/filters/AttributeFilter/tests/utils.ts
yarn.lock

- Search string is reset when dropdown is closed (Apply, Cancel, click outside)
- Fixed use case when items are filtered by search string and user clicks Select All to match behavior of AD/KD
---
--- | ---

BUGFIX: ONE-4060 Reset search string after dropdown close, Select all on subset

---

src/internal/components/pluggableVisualizations/comboChart/PluggableComboChart.tsx
src/internal/components/pluggableVisualizations/comboChart/tests/PluggableComboChart.spec.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2510
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2324
- SD-577: https://jira.intgdc.com/browse/SD-577

BUGFIX: SD-577 add default chart type on saving combo chart

---

src/internal/components/configurationPanels/BaseChartConfigurationPanel.tsx
src/internal/components/configurationPanels/BubbleChartConfigurationPanel.tsx
src/internal/components/configurationPanels/ScatterPlotConfigurationPanel.tsx
src/internal/components/configurationPanels/tests/BaseChartConfigurationPanel.spec.tsx
src/internal/components/configurationPanels/tests/BubbleChartConfigurationPanel.spec.tsx
src/internal/components/configurationPanels/tests/ScatterPlotConfigurationPanel.spec.tsx
src/internal/utils/mdObjectHelper.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2517
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2327
- SD-661: https://jira.intgdc.com/browse/SD-661

BUGFIX: SD-661 Scatter/Bubble chart - Name toggle is enabled

---

src/internal/components/configurationPanels/BubbleChartConfigurationPanel.tsx
src/internal/components/configurationPanels/ScatterPlotConfigurationPanel.tsx
src/internal/components/configurationPanels/tests/BubbleChartConfigurationPanel.spec.tsx
src/internal/components/configurationPanels/tests/ScatterPlotConfigurationPanel.spec.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2519
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2333
- SD-661: https://jira.intgdc.com/browse/SD-661

BUGFIX: SD-661 disable Name section on empty X axis of Scatter/Bubble chart

---

examples/src/components/AttributeFilterComponentExample.jsx
src/components/filters/AttributeFilter/AttributeFilter.tsx
src/components/filters/AttributeFilter/tests/AttributeFilter.spec.tsx
stories/helper_components/AttributeFilter.tsx

onApply handler of Attribute Filter component is now optional to allow only new onApplyWithFilterDefinition to be used
---
--- | ---
Example:
ONE-4151: https://jira.intgdc.com/browse/ONE-4151

BUGFIX: ONE-4151 onApply handler is now optional

---

src/components/core/base/VisualizationLoadingHOC.tsx
src/components/core/base/test/VisualizationLoadingHOC.spec.tsx
src/helpers/errorHandlers.ts
src/helpers/tests/errorHandlers.spec.ts
src/index.ts
src/interfaces/PushData.ts
stories/internal/PossibleDrillableItems.tsx
stories/internal/SupportedDrillableItems.tsx

All visualizations now reports all possibly drillable items (all measures for now). Used in KD to list such items and user can define drill interactions for such items
---
--- | ---
- ONE-4035: https://jira.intgdc.com/browse/ONE-4035

FEATURE: ONE-4035 Pluggable visualization reports drillable measures

---

src/components/core/base/VisualizationLoadingHOC.tsx
src/helpers/errorHandlers.ts
src/helpers/tests/errorHandlers.spec.ts

Invalid NO DATA handling caused that `pushData` promise was not
cancelled properly and was processed even for unmounted visualization.
---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2576
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2397

REALTED: ONE-4035 Fix `pushData` for unmounted PlugableVisualization

---

package.json
yarn.lock

Achieved by upgrading node-sass and upath to versions compatible with Node >= 8. Compatibility with Node 8 is tested on Travis, Node 10 is tested by Heroku examples deploy.
---
--- | ---
- gdc-analytical-designer: N/A as there are no changes in code
- gdc-dashboards: N/A as there are no changes in code

RELATED: FET-392 Make both Node 8 and 10 supported

---

src/internal/components/configurationPanels/BaseChartConfigurationPanel.tsx
src/internal/components/configurationPanels/BubbleChartConfigurationPanel.tsx
src/internal/components/configurationPanels/HeatMapConfigurationPanel.tsx
src/internal/components/configurationPanels/ScatterPlotConfigurationPanel.tsx
src/internal/components/configurationPanels/tests/BaseChartConfigurationPanel.spec.tsx
src/internal/components/configurationPanels/tests/BubbleChartConfigurationPanel.spec.tsx
src/internal/components/configurationPanels/tests/ScatterPlotConfigurationPanel.spec.tsx
src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx
src/internal/utils/propertiesHelper.ts
src/internal/utils/tests/propertiesHelper.spec.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2603
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2422
- SD-726: https://jira.intgdc.com/browse/SD-726

BUGFIX: SD-726 Reporting inconsistency about Axis name in AD vs GD.UI

---

examples/src/components/AttributeFilterComponentExample.jsx
src/components/filters/AttributeFilter/AttributeDropdown.tsx
src/components/filters/AttributeFilter/AttributeFilter.tsx
src/components/filters/AttributeFilter/AttributeLoader.tsx

ProjectId is only optional prop, because it doesn't make sense when URI or Filter by display form URI are used
---
--- | ---
- ONE-4226: https://jira.intgdc.com/browse/ONE-4226

BUGFIX: ONE-4226 ProjectId not relevant when URI prop used

---

src/helpers/MdObjectHelper.ts
src/helpers/tests/MdObjectHelper.spec.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2665
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2465

BUGFIX: SD-743 get length of measures in secondary yAxis config when it existed

---

src/helpers/MdObjectHelper.ts
src/helpers/tests/MdObjectHelper.spec.ts

(cherry picked from commit ff53551c0ab6416c27e15790eb7628992be6f302)
---
--- | ---

BUGFIX: SD-743 get length of measures in yAxis config

---

__mocks__/fixtures.ts
src/constants/visualizationTypes.ts
src/internal/assets/geoPushpin/bucket-title-color.svg
src/internal/assets/geoPushpin/bucket-title-location.svg
src/internal/assets/geoPushpin/bucket-title-segment.svg
src/internal/assets/geoPushpin/bucket-title-size.svg
src/internal/components/BaseVisualization.tsx
src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx
src/internal/components/pluggableVisualizations/geoChart/tests/PluggableGeoPushpinChart.spec.tsx
src/internal/constants/bucket.ts
src/internal/constants/uiConfig.ts
src/internal/mocks/referencePointMocks.ts
src/internal/mocks/uiConfigMocks.ts
src/internal/translations/en-US.json
src/internal/utils/bucketHelper.ts
src/internal/utils/sort.ts
src/internal/utils/tests/sort.spec.ts
src/internal/utils/uiConfigHelpers/geoPushpinChartUiConfigHelper.ts
styles/scss/geoChart.scss

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2707
https://jira.intgdc.com/browse/SD-750
https://jira.intgdc.com/browse/SD-751
https://jira.intgdc.com/browse/SD-752
https://jira.intgdc.com/browse/SD-753
https://jira.intgdc.com/browse/SD-783

FEATURE: SD-750 SD-751 SD-752 SD-753 SD-783 add bucket items and pluggable for geo pushpin

---

examples/src/components/PivotTableSortingAggregationExample.jsx
examples/src/routes/PivotTableDemo.jsx
src/components/core/pivotTable/agGridDataSource.ts
src/components/core/pivotTable/agGridSorting.ts
src/components/core/pivotTable/tests/agGridSorting.spec.ts

RELATED: RAIL-1992 keep attribute sort aggregation in PivotTable

---

.storybook/webpack.config.js
README.md
gdc-ci.yaml
package.json
src/components/core/GeoChart.tsx
src/components/core/base/test/GeoValidatorHOC.spec.tsx
src/components/core/geoChart/GeoChartRenderer.tsx
src/components/core/tests/GeoChart.spec.tsx
src/components/tests/GeoPushpinChart.spec.tsx
src/constants/geoChart.ts
src/interfaces/GeoChart.ts
src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx
stories/core_components/GeoChart.tsx
stories/core_components/GeoPushpinChart.tsx
stories/data/geoChart.ts

How to run Geo chart storybook locally
1. Create Mapbox token as guide [here](https://docs.mapbox.com/help/how-mapbox-works/access-tokens/)
2. Run `yarn install` to install `dotenv-webpack`
3. Run ` STORYBOOK_MAPBOX_ACCESS_TOKEN=your_mapbox_token_here yarn storybook`, or
4. Create `.env` file with content as
```
STORYBOOK_MAPBOX_ACCESS_TOKEN=your_mapbox_token_here
```
5. Run `yarn storybook`
---
--- | ---
See more [options](https://confluence.intgdc.com/display/kbhr/How+to+work+with+git+and+Github#Howtoworkwith …

FEATURE: SETI-3833 add mapbox token prop and inject vault token to storybook test

---

src/components/visualizations/chart/events/setupDrilldownToParentAttribute.ts
src/components/visualizations/chart/events/test/setupDrilldownToParentAttribute.spec.ts
src/components/visualizations/chart/highcharts/commonConfiguration.ts
src/components/visualizations/chart/test/highChartsCreators.spec.ts

Fixing issues for parents attribute drilling in bullet chart:
- The type is bar instead of bullet
- y value for target measure drill event is wrong
---
--- | ---

RELATED: BB-2121 Incorrect parent attribute drilling for bullet chart

---

src/components/core/PivotTable.tsx
src/components/core/tests/PivotTable.spec.tsx

BUGFIX: ONE-4361 Metric column is auto-resized wrongly after sorting

---

src/components/core/PivotTable.tsx

Without the delay, the resulting size was *sometimes* wrong (column was smaller that it's content).
---
--- | ---

BUGFIX: ONE-4368 Add delay to the AgGrid autosizing call

---

src/components/core/PivotTable.tsx
src/components/core/tests/PivotTable.spec.tsx
src/components/tests/mocks.tsx
src/execution/fixtures/ExecuteAfm.fixtures.ts

Column autoresize on onVirtualColumnsChanged can't be done before initial render. Handle tables with row attributes only.
---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2876
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2610

BUGFIX: ONE-4366 Fix of condition when resizing is done

---

src/components/core/PivotTable.tsx

onFirstDataRendered can be called multiple times but we need only one running interval. Currently only one interval was canceled but other running caused infinite call of afterRender handler
---
--- | ---
- gdc-analytical-designer: 
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2624

BUGFIX: ONE-4369 Prevent multiple intervals

---

src/components/visualizations/chart/events/setupDrilldownToParentAttribute.ts
src/components/visualizations/chart/events/test/setupDrilldownToParentAttribute.spec.ts

BUGFIX: BB-2151 Target measure is changed to bar when page is resized

---

package.json
yarn.lock

Fix saveAs button saving old dashboards without layout issue.
Fix saveAs button saving created date in meta.
---
--- | ---

RELATED: RAIL-2131, RAIL-2138 Fix saveAs button behavior

---

src/components/core/geoChart/GeoChartRenderer.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2930
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2650
- SD-898: https://jira.intgdc.com/browse/SD-898

BUGFIX: SD-898 Geo chart cannot render with js error

---

src/components/filters/DateFilter/utils/DateConversions.ts

The problem was that the local time offset was taken for today,
not for the date we are working with.
These are very different if today is DST and the given date is not
or vice versa.
---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2952
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2662

BUGFIX: RAIL-2181 fix date conversion in DateFilter

---

src/components/core/geoChart/GeoChartRenderer.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2975
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2688
SD-908: https://jira.intgdc.com/browse/SD-908

BUGFIX: SD-908 keep zoom after clicking items on category legend

---

src/components/visualizations/chart/chartOptions/bulletChartOptions.ts
src/components/visualizations/chart/events/setupDrilldownToParentAttribute.ts
src/components/visualizations/chart/events/test/setupDrilldownToParentAttribute.spec.ts
src/components/visualizations/utils/drilldownEventing.ts
src/components/visualizations/utils/test/drilldownEventing.spec.tsx

BUGFIX: BB-2180 Bullet chart attribute drilling with null value

---

src/components/core/base/GeoValidatorHOC.tsx
src/components/core/base/test/GeoValidatorHOC.spec.tsx
src/components/core/tests/GeoChart.spec.tsx
src/constants/errorStates.ts
src/helpers/errorHandlers.ts
src/helpers/tests/__snapshots__/errorHandlers.spec.ts.snap
src/translations/en-US.json

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2997
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2712
SD-869: https://jira.intgdc.com/browse/SD-869

FEATURE: SD-869 Geo chart displays friendly message when Mapbox token is missed

---

src/components/core/base/GeoValidatorHOC.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3003
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2720

BUGFIX: SD-922 should re-render geo chart when config or data source changed

---

src/components/core/PivotTable.tsx

BUGFIX: ONE-4376 Use field column identifier in PivotTable resizing

---

examples/webpack.config.js

react-intl must be explicitly transpiled by us, otherwise it won't work in IE11
---
--- | ---

BUGFIX: RAIL-2235 make examples work in IE11

---

src/components/uri/Visualization.tsx
src/helpers/featureFlags.ts

Fixed headline visualization config behaviour. When user sets config disableDrillUnderline it will override featureflag if it is set.
---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3007
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2725

BUGFIX: RAIL-2081 Fix headline visualization config, RAIL-2233 Fix rendering issue of visualization component

---

src/components/core/geoChart/GeoChartRenderer.tsx
src/components/core/geoChart/geoChartDataSource.ts
src/components/visualizations/utils/drilldownEventing.ts
src/components/visualizations/utils/test/drilldownEventing.spec.tsx
src/interfaces/DrillEvents.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3028
- https://client-demo.na.intgdc.com:50029/analyze/
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2746
- https://client-demo.na.intgdc.com:50023/dashboards/
- SD-934: https://jira.intgdc.com/browse/SD-934

BUGFIX: SD-934 SDK - Get wrong value when config tooltipText then drill on geo pushpin

---

src/components/core/geoChart/GeoChartRenderer.tsx
styles/scss/geoChart.scss

---
--- | ---
https://github.com/gooddata/gdc-analytical-designer/pull/3017
Demo is running at https://client-demo.na.intgdc.com:50036/analyze/
https://github.com/gooddata/gdc-dashboards/pull/2736
Demo is running at https://client-demo.na.intgdc.com:50037/dashboards/
https://jira.intgdc.com/browse/SD-931

BUGFIX: SD-931 order position navigator and attribute button

---

src/internal/components/pluggableVisualizations/bulletChart/tests/PluggableBulletChart.spec.tsx
src/internal/components/pluggableVisualizations/bulletChart/tests/bucketHelper.spec.ts
src/internal/components/pluggableVisualizations/scatterPlot/tests/PluggableScatterPlot.spec.tsx
src/internal/utils/bucketHelper.ts
src/internal/utils/tests/bucketHelper.spec.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3097
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2812
- SD-943: https://jira.intgdc.com/browse/SD-943

BUGFIX: SD-943 Measure is removed when switch from geo chart to some charts

---

src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx
src/internal/components/pluggableVisualizations/geoChart/tests/PluggableGeoPushpinChart.spec.tsx
src/internal/mocks/referencePointMocks.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3168
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2884
SD-985: https://jira.intgdc.com/browse/SD-985

BUGFIX: SD-985 ignore show in % in measure on geo chart

---

examples/src/components/PivotTableSizingComplexExample.jsx

BUGFIX: ONE-4517 PivotTable examples button does not work when resize measure width

---

src/components/core/PivotTable.tsx
src/components/core/pivotTable/agGridUtils.ts

To avoid too long properties field in MD we will not create columnWidth definitions for columns which are out of current viewport during batch reset
---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3198
- ONE-4522: https://jira.intgdc.com/browse/ONE-4522

BUGFIX: ONE-4522 Filter out only displayed virtual columns

---

examples/src/components/PivotTableSizingComplexExample.jsx
examples/test/PivotTableSizingReset_test.js
mock-schema.js
src/components/core/PivotTable.tsx
src/components/core/pivotTable/ResizedColumnsStore.ts
src/components/core/pivotTable/agGridColumnSizing.ts
src/components/core/pivotTable/tests/ResizedColumnsStore.spec.ts
src/components/core/pivotTable/tests/agGridColumnSizing.spec.ts
src/helpers/model/tests/widthItems.spec.ts
src/helpers/model/widthItems.ts
src/helpers/tests/featureFlags.spec.ts
src/interfaces/PivotTable.ts
src/internal/components/pluggableVisualizations/pivotTable/tests/widthItemsMock.ts
src/internal/mocks/referencePointMocks.ts
src/internal/utils/tests/propertiesHelper.spec.ts
stories/core_components/PivotTable/ManualResizing.tsx

Handling of manual resize and reset is independent on columnWidths prop of PivotTable so it works for existing and new tables the same.
Reset by double click works together with growToFit
---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3187
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2905
- ONE-4524: …

BUGFIX: ONE-4524 ONE-4527 Handling still the same, new width structure

---

src/components/simple/SyntaxHighlightingInput.tsx
src/components/simple/tests/SyntaxHighlightingInput.spec.tsx

Do not rely on onBlur handling as CodeMirror textarea not always loose its focus and old cursor position is remembered by parent component.
---
--- | ---

BUGFIX: BB-2398 Trigger onCursor each time cursor position changes

---

src/components/visualizations/chart/highcharts/plugins/dataLabelsColors.ts

BUGFIX: ONE-4459 Change stacked chart label to white font

---

src/components/visualizations/chart/highcharts/customConfiguration.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3318
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/3064
SD-582: https://jira.intgdc.com/browse/SD-582

BUGFIX: SD-582 Child label is disappeared when change rotation Y-axis to 90° on Bar chart

---

src/components/visualizations/chart/highcharts/plugins/dataLabelsColors.ts

BUGFIX: ONE-4593 Do not touch labels of line series in combo charts

---

package.json
yarn.lock

This fixes the Spinner keyframes CSS problem.
---
--- | ---
- gdc-analytical-designer: N/A r-c not used there
- gdc-dashboards: N/A r-c not used there

RELATED: RAIL-2675 use up-to-date goodstrap

---

CHANGELOG.md
package.json
src/components/filters/DateFilter/DateFilterBody/DateFilterBody.scss
src/components/filters/DateFilter/DateFilterBody/DateFilterHeader.scss
src/components/filters/DateFilter/DateFilterButton/DateFilterButton.scss
src/components/filters/DateFilter/DateFilterFormWrapper/DateFilterFormWrapper.scss
src/components/filters/DateFilter/Separator/Separator.scss
src/components/visualizations/styles/table.scss
styles/internal/scss/config_panel.scss
styles/scss/measureNumberFormat.scss
styles/scss/measureValueFilter.scss
styles/scss/pivotTable.scss
yarn.lock

`$border-color` was replaced by `$gd-border-color` in this commit
https://github.com/gooddata/gdc-goodstrap/commit/f9ed9c7900f50582b3a7436d0ac31406bc2ffc64
---
--- | ---
- gdc-data-section: https://github.com/gooddata/gdc-data-section/pull/451/

RELATED: SD-1337 Upgrade js-utils and goodstrap to latest version

---

package.json
yarn.lock

AD and KD are no longer use `gooddata-react-components`
---
--- | ---
- gdc-data-section: https://github.com/gooddata/gdc-data-section/pull/452
- SD-1432: https://jira.intgdc.com/browse/SD-1432

RELATED: SD-1432 Upgrade Goodstrap

---

examples/src/index.jsx
examples/webpack.config.js
yarn.lock

* ensure polyfills are loaded first
* align the webpack config with SDK8 which is known to work
Also bump dns-packet to 1.3.4: Closes #1820 
---
--- | ---

RELATED: FET-754 make examples work in IE11, bump dns-packet

---

.github/workflows/check-extended.yaml
.github/workflows/check.yaml
.github/workflows/gate.yaml
.github/workflows/post.yaml

feat(zuul-deprecation): Add workflows
