src/index.ts

Unfortunately I forgot to add default export

RELATED RAIL-286 added catalog helper default export

---

package.json
src/components/core/Table.tsx
yarn.lock

Waiting for new release of `gooddata-indigo-visualizations`. Related pull request: https://github.com/gooddata/gooddata-indigo-visualizations/pull/200

RELATED: BB-328 table totals view mode

---

stories/tsconfig.json

RELATED: RAIL-530 fix - build-storybook is broken when emitting .d.ts files

---

package.json
src/components/simple/Kpi.tsx
src/components/simple/tests/Kpi.spec.tsx
stories/Kpi.tsx

Bugfix for https://github.com/gooddata/gooddata-react-components/pull/124

RELATED: RAIL-272 kpi fix default props

---

package.json
yarn.lock

3.0.0-ocetnik-doc-fix-table-drilling-2017-12-14T12-38-09-533Z

RELATED: BB-503 RAIL-567 Fix drilling for Table and Chart

---

__mocks__/fixtures.ts
src/components/uri/Visualization.tsx
src/components/uri/tests/Visualization.spec.tsx

- added missing totals propagation from prepareDataSources to component state
- added unit test to cover this propagation

BUGFIX: BB-545 add missing totals propagation for Visualization.tsx

---

.storybook/webpack.config.js

Kudos to @ocetnik !
https://github.com/gooddata/gooddata-indigo-visualizations/commit/19395a257aa807b6a23f5fff5b7758918ac30703

RELATED: RAIL-592 Fix broken build-storybook (unexpected token: punc)

---

src/components/core/base/BaseChart.tsx
src/components/core/base/test/BaseChart.spec.tsx

RELATED: RAIL-552 Undo/Redo fires new execution

---

.storybook/webpack.config.js
package.json
yarn.lock

AND:
- revert "uglifyjs punc" hack (because test-storybook@1.0.1 already sorted this out)

RELATED: RAIL-609 test-storybook

---

package.json
yarn.lock

`3.0.1-vaclavbohac-allow-multiple-date-filters-2018-01-19T11-58-58-479Z`

RELATED: RAIL-620 Allow multiple date filters

---

package.json
yarn.lock

- Test-storybook PR: https://github.com/gooddata/gdc-client-utils/pull/85

RELATED: RAIL-633 test-storybook delay for white-label-highchart scenario

---

package.json
src/components/afm/DataSourceProvider.tsx
src/components/afm/tests/utils/DummyExecuteAfmAdapter.tsx
src/components/filters/AttributeFilter/AttributeDropdown.tsx
src/components/filters/AttributeFilter/AttributeElements.tsx
src/components/filters/AttributeFilter/AttributeFilter.tsx
src/components/filters/AttributeFilter/AttributeLoader.tsx
src/components/filters/AttributeFilter/tests/AttributeElements.spec.tsx
src/components/filters/AttributeFilter/tests/AttributeFilter.spec.tsx
src/components/simple/Kpi.tsx
src/components/uri/Visualization.tsx
src/components/uri/tests/Visualization.spec.tsx
src/execution/Execute.tsx
stories/Kpi.tsx
yarn.lock

`@gooddata/react-components@4.0.0-vojty-factory-sdk-2018-03-01T09-57-09-670Z`

RELATED: RAIL-657 Support for multiple domains

---

src/components/core/Headline.tsx
src/components/core/PureTable.tsx
src/components/core/base/BaseChart.tsx
src/components/core/base/BaseVisualization.tsx
src/components/core/base/VisualizationLoadingHOC.tsx
src/components/core/base/test/BaseVisualization.spec.tsx
src/components/core/base/test/VisualizationLoadingHOC.spec.tsx

Demo using this version is running at https://client-demo.na.intgdc.com:50028/analyze/

RELATED: BB-501 Fix broken totals highlight

---

examples/package.json
examples/src/components/DynamicMeasuresExample.jsx
examples/yarn.lock
package.json
src/components/afm/DataSourceProvider.tsx
src/components/afm/tests/utils/DummyExecuteAfmAdapter.tsx
src/components/afm/tests/utils/DummyHeadlineExecuteAfmAdapter.tsx
src/components/core/SortableTable.tsx
src/components/core/base/VisualizationLoadingHOC.tsx
src/components/filters/AttributeFilter/AttributeElements.tsx
src/components/filters/AttributeFilter/AttributeFilter.tsx
src/components/simple/Kpi.tsx
src/components/uri/Visualization.tsx
src/components/uri/tests/Visualization.spec.tsx
src/execution/Execute.tsx
src/execution/tests/Execute.spec.tsx
src/helpers/conversion.ts
src/helpers/errorHandlers.ts
src/helpers/options.ts
src/helpers/tests/errorHandlers.spec.ts
src/helpers/utils.ts
src/interfaces/DataSource.ts
yarn.lock

`5.0.0-vaclavbohac-gooddata-ts-integration-2018-04-04T11-10-49-840Z`

RELATED: FET-53 Add DL from gooddata-js

---

package.json

(cherry picked from commit 0aa4496)

RELATED: FET-72 bugfix when installing pkg as dependency

---

README.md

Added a how to section to the README.md. This should explain how to run live examples locally.

RELATED: RAIL-944 Show users that they can run live examples locally

---

examples/src/components/utils/Header.jsx

Run Locally link now leads to corresponding section inside README.MD on GitHub

RELATED: RAIL 944

---

src/components/visualizations/chart/chartOptionsBuilder.ts
src/components/visualizations/chart/test/chartOptionsBuilder.spec.ts

PR for [SD-68](https://jira.intgdc.com/browse/SD-68)

BUGFIX: SD-68 label on yaxis of heatmap are broken when measure is formatted in percent

---

src/components/core/Headline.tsx
src/components/core/tests/Headline.spec.tsx
src/components/visualizations/Visualization.tsx
src/components/visualizations/chart/ChartTransformation.tsx
src/components/visualizations/table/TableTransformation.tsx
src/components/visualizations/table/TableVisualization.tsx
src/components/visualizations/utils/drilldownEventing.ts
src/index.ts
src/interfaces/DrillEvents.ts
src/interfaces/Events.ts
src/proptypes/Headline.ts

This reverts commit ff85773d7973c93d9bc7c1c4b0974b52fa47ca26.

Revert "BUGFIX: BB-1080 onFireDrillEvent fix"

---

package.json
src/components/afm/tests/DataSourceProvider.spec.tsx
src/components/core/PivotTable.tsx
src/components/core/base/VisualizationLoadingHOC.tsx
yarn.lock

`5.2.0-ocetnik-doc-export-paging-2018-07-31T12-30-56-482Z`

RELATED: RAIL-1016 Upgrade gooddata-js and typings

---

src/components/visualizations/chart/highcharts/heatMapConfiguration.ts
src/components/visualizations/utils/drilldownEventing.ts
src/components/visualizations/utils/test/drilldownEventing.spec.tsx

PR for [SD-85](https://jira.intgdc.com/browse/SD-85) and [SD-86](https://jira.intgdc.com/browse/SD-86)

BUGFIX: SD-85 hand mouse should display on drillable heatmap cell

---

src/components/visualizations/chart/HighChartsRenderer.tsx
src/components/visualizations/chart/highcharts/heatmapConfiguration.ts
src/components/visualizations/chart/test/HighChartsRenderer.spec.tsx
src/components/visualizations/chart/test/highChartsCreators.spec.ts

This reverts commit b95bb2c0f5553412440da07ae0ffa042ac552ee3.

Revert "BUGFIX: SD-90 remove the top number on yaxis of heatmap"

---

examples/src/components/PivotTableDynamicExample.jsx
examples/src/utils/helpers.js
src/components/PivotTable.tsx
src/helpers/errorHandlers.ts
src/helpers/tests/errorHandlers.spec.ts

FEATURE: RAIL-1143 PivotTable: log warning into console when localIdentifiers are not unique

---

src/components/uri/Visualization.tsx
src/components/uri/tests/Visualization.spec.tsx

BUGFIX: ONE-3457 Don't wait for palette

---

examples/src/components/PivotTableDynamicExample.jsx
examples/test/Menu_test.js
examples/test/PivotTableDynamic_test.js
examples/test/utils/helpers.js
package.json
src/components/core/pivotTable/HeaderCell.tsx
yarn.lock

- `testcafe-live` dependency was added after consulting with @tomasreichmann. It makes development of tests easier since it watches for tests changes and automatically reruns them.

FEATURE: RAIL-1255 Cafe tests for header menu

---

CHANGELOG.md
examples/src/components/ArithmeticMeasureChangeExample.jsx

Merge back freshly released 6.2.0 in `master` to `next-6.3.0`

master (6.2.0) to next 6.3.0

---

examples/src/components/BarChartExportExample.jsx
examples/src/components/PivotTableExportExample.jsx
examples/src/components/TableExportExample.jsx
examples/src/components/VisualizationColumnChartExportExample.jsx
examples/src/components/utils/ExampleWithExport.jsx
examples/src/routes/Export.jsx
examples/src/routes/_list.js
src/components/afm/DataSourceProvider.tsx
src/components/afm/tests/DataSourceProvider.spec.tsx
src/components/core/base/BaseChart.tsx
src/components/core/base/VisualizationLoadingHOC.tsx
src/components/core/base/test/VisualizationLoadingHOC.spec.tsx
src/components/uri/Visualization.tsx
src/components/uri/tests/Visualization.spec.tsx
src/interfaces/Events.ts
stories/internal/Export.tsx

PR for [SD-180](https://jira.intgdc.com/browse/SD-180)
- Export for Chart/Table/Pivot Table/Visualization components
- Add Export examples (menu Export)
- Add Export storybook (Internal/Export)
- Spike: https://docs.google.com/document/d/1TGs3awVQjAU7N8CLAVRO_-MPlpP33EWgoOwBXTbpuQ4/edit#

FEATURE: SD-180 - Export in UI SDK

---

src/components/core/PivotTable.tsx

Tested in
* https://github.com/gooddata/gdc-analytical-designer/pull/1973 ✅ (there is a demo running with repro steps)
* https://github.com/gooddata/gdc-dashboards/pull/1573 ✅
Via https://github.com/gooddata/gdc-app-components/pull/463

BUGFIX: RAIL-1218 compare pivot dataSource properly, improve legibility

---

src/components/core/PivotTable.tsx
src/components/core/base/VisualizationLoadingHOC.tsx
src/components/core/base/test/VisualizationLoadingHOC.spec.tsx
src/components/core/pivotTable/HeaderCell.tsx
src/components/menu/ControlledMenu.tsx
src/components/menu/Menu.tsx
src/components/menu/menuOpener/MenuOpenedByClick.tsx
src/components/menu/menuOpener/MenuOpenedByHover.tsx
src/components/menu/menuOpener/MenuOpenedBySharedProps.ts
src/components/menu/menuOpener/MenuOpener.tsx
src/components/menu/positioning/MenuPosition.tsx
src/components/menu/tests/__snapshots__/Menu.spec.tsx.snap
stories/data/componentProps.ts
styles/scss/menu.scss
styles/scss/pivotTable.scss

This PR includes a cosmetic fix of PivotTable's menu button, that overflows it's row by 2 pixels and some light refactoring of some Menu components.

BUGFIX: RAIL-1287 Cannot add table total for (empty value) on column header

---

src/components/visualizations/chart/events/load.ts
src/components/visualizations/chart/highcharts/commonConfiguration.ts
src/components/visualizations/chart/test/highChartsCreators.spec.ts
src/components/visualizations/chart/test/loadEvent.spec.ts

Jira:
[SD-210](https://jira.intgdc.com/browse/SD-210)

SD-210 add selenium class names to Y axis for dual axes chart

---

package.json
src/components/uri/tests/Visualization.spec.tsx
src/components/visualizations/chart/highcharts/plugins/test/getTickPositions.spec.ts
src/components/visualizations/chart/highcharts/plugins/zeroAlignYAxis.ts
src/components/visualizations/table/test/ResponsiveTable.spec.tsx
yarn.lock

Client Demo: https://client-demo.na.intgdc.com:50017/analyze/
PR for testing in AD: https://github.com/gooddata/gdc-analytical-designer/pull/1998

BUGFIX: SD-265 SDK: Grid lines are duplicated and align # 0

---

package.json
yarn.lock

Fix datepicker in chinese locale

RELATED: SD-208 upgrade goodstrap version

---

src/components/core/base/VisualizationLoadingHOC.tsx
src/components/core/base/test/VisualizationLoadingHOC.spec.tsx

PR for [SD-294](https://jira.intgdc.com/browse/SD-294)
Demos:
- AD: https://github.com/gooddata/gdc-analytical-designer/pull/2048
- KD: https://github.com/gooddata/gdc-dashboards/pull/1654
Check list

BUGFIX: SD-294: Export previous result after filter out no data

---

examples/src/components/HeadlineExportExample.jsx
examples/src/components/TableExportExample.jsx
examples/src/routes/Export.jsx
src/components/afm/DataSourceProvider.tsx
src/components/afm/Headline.ts
src/components/afm/tests/DataSourceProvider.spec.tsx
stories/internal/Export.tsx

PR for [SD-285](https://jira.intgdc.com/browse/SD-285)
Related PRs
- app-components: https://github.com/gooddata/gdc-app-components/pull/489
- AD: https://github.com/gooddata/gdc-analytical-designer/pull/2045
Demo
- AD: https://github.com/gooddata/gdc-analytical-designer/pull/2042/
- KD: https://github.com/gooddata/gdc-dashboards/pull/1636
Check list

BUGFIX: SD-285 - Support Export for Headline in UI SDK

---

package.json
yarn.lock

PR for [SD-300](https://jira.intgdc.com/browse/SD-300)
- This PR fixes the duplicated goodstrap in yarn.lock

BUGFIX: SD-300 - bump version

---

src/components/visualizations/chart/highcharts/getOptionalStackingConfiguration.ts
src/components/visualizations/chart/highcharts/test/getOptionalStackingConfiguration.spec.ts

---
AD: https://github.com/gooddata/gdc-analytical-designer/pull/2075
KD: https://github.com/gooddata/gdc-dashboards/pull/1698

BUGFIX: SD-317 handle % from AM Change and stackMeasuresToPercent

---

package.json
yarn.lock

gdc-goodstrap: https://github.com/gooddata/gdc-goodstrap/pull/934
gooddata-react-components: https://github.com/gooddata/gooddata-react-components/pull/834
gdc-app-components: https://github.com/gooddata/gdc-app-components/pull/506
gdc-goodstrap: https://github.com/gooddata/gdc-dashboards/pull/1704
gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2078

RELATED: FET-280 update goodstrap

---

src/components/core/PivotTable.tsx

https://github.com/gooddata/gdc-app-components/pull/514
https://github.com/gooddata/gdc-analytical-designer/pull/2088 ✅
https://github.com/gooddata/gdc-dashboards/pull/1721 ✅

BUGFIX: RAIL-1340 handle maxHeight on column resize

---

src/components/visualizations/chart/highcharts/customConfiguration.ts
src/components/visualizations/chart/highcharts/test/customConfiguration.spec.ts

---
AD: https://github.com/gooddata/gdc-analytical-designer/pull/2059
KD: https://github.com/gooddata/gdc-dashboards/pull/1672

BUGFIX: SD-309 SDK gets JS error when deselect an attribute value in legend

---

src/components/visualizations/chart/highcharts/getOptionalStackingConfiguration.ts
src/components/visualizations/chart/highcharts/test/getOptionalStackingConfiguration.spec.ts

---
AD: https://github.com/gooddata/gdc-analytical-designer/pull/2071
KD: https://github.com/gooddata/gdc-dashboards/pull/1690

BUGFIX: SD-311 SD-312 disable stacking measure config when there is one measure/series

---

src/helpers/dimensions.ts
src/helpers/tests/dimensions.spec.ts

RELATED: SD-302 generate dimensions for area with two view items

---

package.json
yarn.lock

- gdc-goodstrap: https://github.com/gooddata/gdc-goodstrap/pull/939
- gooddata-react-components: https://github.com/gooddata/gooddata-react-components/pull/875
- gdc-app-components: https://github.com/gooddata/gdc-app-components/pull/527
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/1791
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2127

RELATED: RAIL-1389 SDK throws errors when used in custom app

---

src/components/visualizations/chart/chartOptionsBuilder.ts
src/components/visualizations/chart/test/chartOptionsBuilder.spec.ts
src/components/visualizations/chart/test/helper.ts

PR for [SD-331](https://jira.intgdc.com/browse/SD-331)
---
- Add new tooltip function for Bar and Column charts with 2 attributes
- Add Unit tests
---
---
- https://github.com/gooddata/gdc-analytical-designer/pull/2135
- https://github.com/gooddata/gdc-dashboards/pull/1808

BUGFIX: SD-331 - Display full information in tooltip for Optional Stacking

---

examples/test/VisualizationByIdentifier_test.js
examples/test/VisualizationByUri_test.js

RELATED: BB-1385 fixed live testcafe tests with enablePivot FF

---

.storybook/test-storybook.config.js
src/components/core/PivotTable.tsx
src/components/core/tests/PivotTable.spec.tsx

TRIVIAL: fixed storybook flaky pivot-table

---

src/components/core/pivotTable/stickyGroupHandler.ts
src/components/core/pivotTable/tests/stickyGroupHandler.spec.ts

BUGFIX: BB-1477 fixed pivot sticky row overflow

---

examples/test/PivotTableDynamic_test.js
styles/scss/pivotTable.scss

BUGFIX: BB-1473 Fix pivot table sticky headers in combination with formatting

---

src/components/core/PivotTable.tsx
src/helpers/agGrid.ts
src/helpers/tests/agGrid.spec.ts

BUGFIX: BB-1493 escaping in pivotTable to prevent xss

---

styles/scss/pivotTable.scss

BUGFIX: RAIL-1330 RAIL-1442 Width & bg of PivotTable menu

---

examples/test/PivotTableDynamic_test.js
examples/test/PivotTableMenu_test.js
src/components/visualizations/chart/chartOptionsBuilder.ts
src/components/visualizations/chart/highcharts/customConfiguration.ts
src/components/visualizations/chart/highcharts/test/customConfiguration.spec.ts

--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2183
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/1879
- SD-384: https://jira.intgdc.com/browse/SD-384

BUGFIX: SD-384 apply 'follow pointer' to combo chart

---

package.json
yarn.lock

Core of the changes: https://github.com/gooddata/gdc-goodstrap/pull/943
--- | ---
- gdc-app-components: https://github.com/gooddata/gdc-app-components/pull/547
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2191
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/1887
- [RAIL-1454](https://jira.intgdc.com/browse/RAIL-1454)

RELATED: RAIL-1454 allow opt-in event propagation

---

src/components/core/PivotTable.tsx
src/components/core/tests/PivotTable.spec.tsx

RELATED: BB-1490 fixed sticky row error when table is hidden

---

examples/test/PivotTableDynamic_test.js
src/components/core/PivotTable.tsx
src/components/core/pivotTable/aggregationsMenuHelper.ts
src/components/core/pivotTable/tests/aggregationsMenuHelper.spec.ts

BUGFIX: BB-1508 fixed subtotals burgermenu behaviour

---

src/translations/de-DE.json
src/translations/fr-FR.json
src/translations/nl-NL.json
src/translations/pt-BR.json
src/translations/zh-Hans.json

RELATED: BB-1475 Fix translations

---

src/translations/en-US.json

TRIVIAL: Update translation comment

---

src/components/core/PivotTable.tsx
src/components/core/pivotTable/stickyGroupHandler.ts
src/components/core/pivotTable/tests/stickyGroupHandler.spec.ts
src/components/core/tests/PivotTable.spec.tsx

RELATED: BB-1490 fixed sticky row error when sticky row doesnt exist

---

src/translations/es-ES.json
src/translations/pt-BR.json
src/translations/pt-PT.json

RELATED: BB-1506 Fix translations

---

examples/test/PivotTableDynamic_test.js
examples/test/PivotTableMenu_test.js

BUGFIX: BB-1505 fixed flaky total testcafe

---

styles/scss/pivotTable.scss

RELATED: BB-1470 Fix placeholder sticky cell border

---

src/translations/es-ES.json

TRIVIAL: Fix aggregation translation

---

src/translations/en-US.json

TRIVIAL: Add transaltion instructions

---

examples/src/components/ResponsiveExample.jsx
package.json
src/components/visualizations/chart/legend/Legend.tsx
src/components/visualizations/table/Table.tsx
yarn.lock

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2208
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/1922

FEATURE: FET-293 react-measure

---

src/components/simple/Fireworks.tsx
src/components/simple/LoadingComponent.tsx

FEATURE: FET-28 SDK easter egg

---

examples/src/components/ConfigurationColumnChartExample.jsx
examples/src/routes/ChartConfiguration.jsx
examples/src/utils/fixtures.js
examples/test/ChartConfiguration_test.js

- add 2 buttons change legend and change separator to customize for visualization insight and bucket component insight.
- add new identifier for column chart 
- add new test for chart configuration

FEATURE: QA-9454 Customize embedded insight on SDK dashboard (TestCafe)

---

src/components/core/pivotTable/AggregationsSubMenu.tsx

---
--- | ---
- gdc-analytical-designer: 
- BB-1413: https://jira.intgdc.com/browse/BB-1413

RELATED: BB-1413 selected subtotal item s-class

---

src/components/visualizations/chart/chartOptions/extendedStackingChartOptions.ts
src/components/visualizations/chart/chartOptions/test/extendedStackingChartOptions.spec.ts

---
--- | ---
- gdc-app-components: https://github.com/gooddata/gdc-app-components/pull/563
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2223
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/1949
- SD-425: https://jira.intgdc.com/browse/SD-425

BUGFIX: SD-425 Different reports in case of loading NULL fact

---

src/components/core/pivotTable/agGridApiWrapper.ts
src/components/core/pivotTable/agGridDataSource.ts
src/components/core/pivotTable/tests/agGridApiWrapper.spec.tsx
src/components/core/pivotTable/tests/agGridDataSource.spec.ts

RELATED: BB-1502 Fix invalid offset paging

---

__mocks__/fixtures.ts
examples/src/components/VisualizationTableByIdentifierExample.jsx
src/components/PivotTable.tsx
src/components/uri/Visualization.tsx
src/helpers/MdObjectHelper.ts
src/helpers/afmHelper.ts
src/helpers/tests/MdObjectHelper.spec.ts
src/helpers/tests/afmHelper.spec.ts

BUGFIX: RAIL-1469 SDK: Can't add Rollup (totals) on visualization component

---

styles/scss/pivotTable.scss

RELATED: BB-1518 Sticky cell next to subtotal is bold

---

src/components/core/pivotTable/agGridApiWrapper.ts
src/components/core/pivotTable/agGridDataSource.ts
src/components/core/pivotTable/tests/agGridApiWrapper.spec.tsx
src/components/core/pivotTable/tests/agGridDataSource.spec.ts

RELATED: BB-1502 Fix PivotTable offset paging issue

---

styles/scss/pivotTable.scss

RELATED: BB-1500 Burger menu in Safari

---

package.json
yarn.lock

RELATED: BB-1516 Upgrade dependency

---

CHANGELOG.md
src/components/visualizations/utils/drilldownEventing.ts
src/interfaces/Config.ts
src/interfaces/DrillEvents.ts

Merge master (6.3.2) to next 7.0.0

---

package.json
yarn.lock

--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2235
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/1956

RELATED: RAIL-1531 add mock-js with support for DateFilterConfig

---

src/components/uri/Visualization.tsx
src/helpers/MdObjectHelper.ts

Merge next-7.0.0 into next-7.1.0

---

examples/src/components/AttributeFilterComponentExample.jsx
examples/src/components/AttributeFilterExample.jsx
examples/src/components/MonthPickerExample.jsx
examples/src/routes/AttributeFilter.jsx
examples/src/routes/DatePicker.jsx
examples/src/utils/fixtures.js
examples/test/AttributeFilter_test.js
examples/test/DatePicker_test.js

- change AttributeFilterExample.jsx -> AttributeFilterComponentExample.jsx
- add new file AttributeFilterExample.jsx to get example for attribute filter component apply to chart
- add month picker examples at /advanced/date-picker
- add test for attribute filter and month picker
- add some identifier in fixture

FEATURE: QA-9573 Filter embedded insight (basic - TestCafe)

---

CHANGELOG.md
README.md

TRIVIAL: Update changelog

---

styles/scss/pivotTable.scss

RELATED: BB-1525 PivotTable cell shortening in attribute columns

---

.gitignore
.storybook/preview-head.html
.storybook/webpack.config.js
scripts/build.sh
src/internal/components/configurationControls/colors/ColorsSection.tsx
src/internal/components/configurationControls/colors/coloredItemsList/ColoredItemsList.tsx
src/internal/components/configurationControls/colors/coloredItemsList/tests/ColoredItemsList.spec.tsx
src/internal/components/configurationControls/colors/tests/ColorsSection.spec.tsx
stories/internal/pluggable_visualization/configurationControls/Colors/ColorDropdown.tsx
stories/internal/pluggable_visualization/configurationControls/Colors/ColorPalette.tsx
stories/internal/pluggable_visualization/configurationControls/Colors/ColoredItemsList.tsx
stories/tsconfig.json
stories/utils/IntlDecorators.tsx
stories/utils/ScrollNotificationDiv.tsx
stories/utils/SmallScreenDecorator.tsx
stories/utils/SmallScrollDecorator.tsx

RELATED: FET-225 Moved stories from app-components

---

src/components/AreaChart.tsx
src/components/BarChart.tsx
src/components/ColumnChart.tsx
src/components/ComboChart.tsx
src/components/tests/ComboChart.spec.tsx
src/helpers/dimensions.ts
src/helpers/dualAxis.ts
src/helpers/mdObjBucketHelper.ts
src/helpers/optionalStacking/common.ts
src/helpers/optionalStacking/test/common.spec.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2236
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/1965

FEATURE: SD-446 Unify behavior of stackMeasuresToPercent and computeRatio on Combo chart

---

.github/pull_request_template.md

TRIVIAL: Remove mention of the app-components from GitHub PR template

---

examples/src/components/PivotTableDrillExample.jsx
examples/test/PivotTableDrillExample_test.js
jest.setup.js
src/components/core/PivotTable.tsx
src/components/core/pivotTable/agGridConst.ts
src/components/core/pivotTable/agGridData.ts
src/components/core/pivotTable/agGridTypes.ts
src/components/core/pivotTable/agGridUtils.ts
src/components/core/pivotTable/tests/agGridData.spec.ts
src/components/core/pivotTable/tests/agGridDataSource.spec.ts

FEATURE: BB-1416 disable drilling on totals and subtotals

---

src/components/core/PivotTable.tsx
src/components/core/pivotTable/ColumnHeader.tsx
src/components/core/pivotTable/tests/ColumnHeader.spec.tsx
src/components/core/tests/PivotTable.spec.tsx

BUGFIX: BB-1562 Fix aggregation menu appearing on attribute headers

---

src/helpers/tests/errorHandlers.spec.ts
src/index.ts
tsconfig.build.json
tsconfig.dev.json

RELATED: FET-225 Exclude internals from main index.ts

---

src/internal/components/configurationPanels/ConfigurationPanelContent.tsx

Revert this line: https://github.com/gooddata/gooddata-react-components/pull/1009/files#diff-972eb02cdb0c34cb0834aeda3fda4d22L52
---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2279
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2013

RELATED: FET-225 Fix fail testcafe tests

---

src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
src/internal/components/pluggableVisualizations/pivotTable/tests/PluggablePivotTable.spec.tsx

RELATIVE: BB-1386 Remove enablePivotSubtotal feature flag

---

examples/src/components/BarChartExportExample.jsx
examples/src/components/HeadlineExportExample.jsx
examples/src/components/PivotTableExportExample.jsx
examples/src/components/TableExportExample.jsx
examples/src/components/VisualizationColumnChartExportExample.jsx
examples/src/components/utils/ExampleWithExport.jsx
package.json
stories/internal/Export.tsx
yarn.lock

PR for [SD-467](https://jira.intgdc.com/browse/SD-467)
---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2264
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2007
- SD-467: https://jira.intgdc.com/browse/SD-467

FEATURE: SD-467 - Support "Active filters context" in SDK

---

src/components/core/pivotTable/agGridDataSource.ts
src/components/core/pivotTable/agGridDataSourceUtils.ts
src/components/core/pivotTable/tests/RowLoadingElement.spec.tsx
src/components/core/pivotTable/tests/agGridDataSource.spec.ts
src/components/core/pivotTable/tests/agGridDataSourceUtils.spec.ts

RELATED: BB-1526 Remove duplicated executionResult request

---

styles/scss/pivotTable.scss

RELATED: BB-1564 Remove useless scrollbar for grand totals

---

examples/src/components/PivotTableXssExample.jsx
examples/src/routes/PivotTableXss.jsx
examples/src/routes/_list.js
examples/test/PivotTableXss_test.js
examples/test/utils/helpers.js
src/components/core/pivotTable/agGridUtils.ts
src/components/core/pivotTable/tests/agGridUtils.spec.ts
src/components/simple/Kpi.tsx
src/components/visualizations/chart/chartOptionsBuilder.ts
src/components/visualizations/chart/highcharts/customConfiguration.ts
src/components/visualizations/chart/tooltip.ts
src/components/visualizations/headline/utils/HeadlineDataItemUtils.ts
src/components/visualizations/utils/common.ts
src/helpers/numberFormatting.ts
src/helpers/tableCell.ts
src/helpers/tests/numberFormatting.spec.ts

--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2284
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2021

RELATED: RAIL-1585 improve XSS prevention

---

src/components/visualizations/chart/highcharts/dataLabelsHelpers.ts
src/components/visualizations/chart/highcharts/plugins/dualAxesLabelFormatter.ts

TRIVIAL: SD-484 Explain the existence of 'this' inside functions

---

src/components/visualizations/chart/highcharts/getOptionalStackingConfiguration.ts
src/components/visualizations/chart/highcharts/plugins/dualAxesLabelFormatter.ts
src/components/visualizations/chart/highcharts/plugins/test/dualAxesLabelFormatter.spec.ts
src/components/visualizations/chart/highcharts/test/getOptionalStackingConfiguration.spec.ts
src/internal/components/pluggableVisualizations/comboChart/PluggableComboChart.tsx
src/internal/components/pluggableVisualizations/comboChart/tests/PluggableComboChart.spec.tsx
src/internal/constants/uiConfig.ts
src/internal/interfaces/Visualization.ts

--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2281
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2015

FEATURE: SD-481 disable stack checkbox for line chart type in combo

---

package.json
yarn.lock

--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2301/files
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2056/files

RELATED: ONE-3859 Use downgraded react-date-picker

---

examples/src/components/BarChartExportExample.jsx
examples/src/components/PivotTableExportExample.jsx
examples/src/components/TableExportExample.jsx
examples/src/components/VisualizationColumnChartExportExample.jsx
examples/src/components/utils/ExampleWithExport.jsx
src/components/core/base/VisualizationLoadingHOC.tsx
src/components/core/base/test/VisualizationLoadingHOC.spec.tsx
src/components/tests/mocks.tsx
src/execution/fixtures/ExecuteAfm.fixtures.ts
src/interfaces/Events.ts
stories/internal/Export.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2304
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2058
- SD-501: https://jira.intgdc.com/browse/SD-501
- SD-510: https://jira.intgdc.com/browse/SD-510

BUGFIX: SD-510 - Export with Active filters context refactor

---

package.json
yarn.lock

--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2299
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2047

BUGFIX: SD-502 apply release gooddata js deps

---

src/internal/components/pluggableVisualizations/comboChart/PluggableComboChart.tsx
src/internal/components/pluggableVisualizations/comboChart/tests/PluggableComboChart.spec.tsx
src/internal/mocks/referencePointMocks.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2293
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2032

BUGFIX: SD-500 Keep percent config if there is one measure

---

package.json
yarn.lock

RELATED: FET-159 Upgrade test-storybook dependency

---

src/components/core/pivotTable/agGridUtils.ts
src/components/core/pivotTable/tests/agGridUtils.spec.ts
src/components/visualizations/headline/utils/HeadlineDataItemUtils.ts
src/helpers/tableCell.ts

--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2313
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2070

RELATED: RAIL-1623 fix XSS protection in PivotTable and Headline

---

package.json
yarn.lock

RELATED: FET-159 Using react and gooddata dependencies with carets

---

CHANGELOG.md

TRIVIAL: SD-510 Update changelog

---

package.json
yarn.lock

Using upgraded d.ts for VisualizationsListItem. This was not used anywhere but need to pass up through the codebase because this is a semver major change.
--- | ---

RELATED: ONE-3742 Use upgraded GS with d.ts

---

src/internal/components/pluggableVisualizations/comboChart/tests/PluggableComboChart.spec.tsx

BUGFIX: SD-527 fix promises in combination with forEach in unit test for combo

---

.github/pull_request_template.md

TRIVIAL: remove app-components from PR template

---

src/execution/Execute.tsx

TRIVIAL: fix typo in Exectute component

---

examples/src/components/BucketExecutorExample.jsx
examples/src/routes/BucketExecutor.jsx
examples/src/routes/_list.js
jest.setup.js
src/execution/BucketExecutor.tsx
src/execution/tests/BucketExecutor.spec.tsx
src/index.ts

FEATURE: RAIL-1634 create a bucket executor component for react components

---

src/components/visualizations/utils/drilldownEventing.ts
src/components/visualizations/utils/test/drilldownEventing.spec.tsx
src/constants/series.ts
src/helpers/visualizationType.ts
src/interfaces/DrillEvents.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2324
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2081

FEATURE: SD-469 Drilling in Combo chart

---

.github/CODEOWNERS

TRIVIAL: Add PJA to codeowners file

---

yarn.lock

--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2336
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2100

RELATED: FET-326 replace event observables by event listeners

---

CHANGELOG.md
src/components/core/PivotTable.tsx
src/components/core/tests/PivotTable.spec.tsx

* Fix drill event intersection element id. Item localIdentifier has higher priority over measure/attribute id
---
--- | ---

RELATED: BB-1589 Fix incorrect drill intersection element id

---

CHANGELOG.md
src/components/core/PivotTable.tsx
src/components/core/tests/PivotTable.spec.tsx

RELATED: BB-1589 Fix incorrect drill intersection element id for 7.0.0 version

---

package.json
yarn.lock

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2352
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2125
- SD-530: https://jira.intgdc.com/browse/SD-530

RELATED: SD-530 Can't export insight with filter by string

---

package.json
yarn.lock

FEATURE: FET-319 Reformat source code with Prettier upon a commit

---

.travis.yml

Fix failed trvis-ci check in https://travis-ci.org/gooddata/gooddata-react-components/jobs/557103685

CONFIG: upgrade node version in travis-ci

---

src/components/visualizations/chart/highcharts/heatmapConfiguration.ts
src/components/visualizations/chart/highcharts/test/heatmapConfiguration.spec.ts
src/interfaces/HighchartsExtend.ts

--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2348
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2120
- [SD-532](https://jira.intgdc.com/browse/SD-532)

BUGFIX: SD-532 negative heatmap cells height error

---

package.json
yarn.lock

---
--- | ---
https://github.com/gooddata/gdc-analytical-designer/pull/2373
https://github.com/gooddata/gdc-dashboards/pull/2146
https://github.com/gooddata/gooddata-react-components/pull/1104
https://github.com/gooddata/gdc-goodstrap/pull/966

RELATED: ONE-3905 Properly remove foundations

---

examples/webpack.config.js
package.json
scripts/build-examples.sh
yarn.lock

--- | ---
Not applicable, there are no changes in published code.

RELATED: FET-344 simplify examples build definition

---

src/components/visualizations/chart/highcharts/commonConfiguration.ts

--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2380
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2161
- SD-549: https://jira.intgdc.com/browse/SD-549

BUGFIX: SD-549 set active datalabels color

---

package.json
yarn.lock

RELATED: ONE-891 Bump `@gooddata/goodstrap`

---

package.json
yarn.lock

Merge `next-7.1.0` into `next-7.2.0`

---

package.json
yarn.lock

RELATED: ONE-3891 Bump `@gooddata/goodstrap`

---

CHANGELOG.md

Updated changelog
---
--- | ---

RELATED: ONE-3918 updated changelog

---

CHANGELOG.md
src/components/uri/Visualization.tsx
src/components/uri/tests/Visualization.spec.tsx

Propagate external SDK instance into PivotTable
---
--- | ---
- ONE-3932: https://jira.intgdc.com/browse/ONE-3932

BUGFIX: ONE-3932 Propagate external SDK to pivot table

---

package.json
src/components/withJsxExport.tsx
src/helpers/model/filters.ts
src/helpers/model/objectToModelNotation.ts
src/helpers/model/tests/measures.spec.ts
src/helpers/model/tests/objectToModelNotation.spec.ts
src/index.ts
yarn.lock

--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2371
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2142

RELATED: RAIL-1651 add export as JSX functionality

---

CHANGELOG.md
src/components/uri/Visualization.tsx
src/components/uri/tests/Visualization.spec.tsx

Merged master to next-7.2.0
---
--- | ---

RELATED: ONE-3918 cleanup

---

package.json
yarn.lock

--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2403
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2187

RELATED: FET-340 use goodstrap without findDOMNode

---

src/components/visualizations/chart/highcharts/comboConfiguration.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2402
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2186
- SD-571: https://jira.intgdc.com/browse/SD-571

BUGFIX: SD-571 weird highlighting with Combo chart

---

examples/src/components/MonthPickerExample.jsx
examples/test/DatePicker_test.js
src/components/core/PivotTable.tsx
src/components/core/tests/PivotTable.spec.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2386
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2196
- SD-569: https://jira.intgdc.com/browse/SD-569

FEATURE: SD-569 call afterRender in PivotTable

---

yarn.lock

RELATED: ONE-3942 Update @gooddata/typings

---

src/components/visualizations/headline/Headline.tsx

--- | ---
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2190
https://jira.intgdc.com/browse/SD-358

FEATURE: SD-358 add tooltip for headline

---

yarn.lock

This reverts commit 4f9810fa91fcc367ca12e31b8658a1b1d2570889.
---
--- | ---

Revert "RELATED: ONE-3942 Update @gooddata/typings"

---

package.json
yarn.lock

--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2414
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2204

RELATED: RAIL-1682 use updated goodstrap

---

yarn.lock

RELATED: ONE-3942 Update mock.js reference

---

src/components/core/PivotTable.tsx
src/components/core/base/VisualizationLoadingHOC.tsx
src/components/core/base/test/VisualizationLoadingHOC.spec.tsx
src/components/core/pivotTable/agGridUtils.ts
src/components/core/pivotTable/tests/agGridUtils.spec.ts
src/components/core/tests/PivotTable.spec.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2418
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2207

RELATED: BB-1657 Fix broken pivot table reset

---

examples/test/VisualizationByIdentifier_test.js

TRIVIAL: Fix unstable testcafe test

---

package.json
yarn.lock

RELATED: BB-1569 upgraded gooddata-js

---

package.json

By just changing the description in package.json. The description is copied from our web.
---
--- | ---

TRIVIAL: FET-361 Tests auto beta release

---

package.json
src/components/uri/Visualization.tsx
yarn.lock

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2444
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2231

RELATED: RAIL-1719 handle projectId change in Visualization properly

---

package.json
yarn.lock

RELATED: FET-285 upgrade eslint config

---

package.json
yarn.lock

RELATED: ONE-3948 Update dependences goodstrap

---

package.json
yarn.lock

RELATED: ONE-3948 Update references

---

examples/src/components/BarChartDynamicExample.jsx
examples/src/components/ConfigurationColumnChartExample.jsx
examples/src/components/DynamicMeasuresExample.jsx

BUGFIX: FET-370 Fix issues with some live examples

---

examples/src/components/utils/ExampleWithSource.jsx
package.json
yarn.lock

BUGFIX: ONE-4045 Fix syntax highlighting in Execute Component example

---

CHANGELOG.md
examples/src/components/MeasureValueFilterExample.jsx
examples/src/routes/MeasureValueFilter.jsx
examples/src/routes/_list.js
examples/test/MeasureValueFilter_test.js
src/components/visualizations/proptypes/execution.ts
yarn.lock

FEATURE: BB-1690 Support measure value filters in UI SDK

---

examples/src/components/AttributeFilterComponentExample.jsx
examples/src/components/AttributeFilterExample.jsx
examples/src/utils/fixtures.js
examples/test/AttributeFilter_test.js
src/components/filters/AttributeFilter/AttributeDropdown.tsx
src/components/filters/AttributeFilter/AttributeFilter.tsx
src/components/filters/AttributeFilter/AttributeLoader.tsx
src/components/filters/AttributeFilter/tests/AttributeDropdown.spec.tsx
src/components/filters/AttributeFilter/tests/AttributeElements.spec.tsx
src/components/filters/AttributeFilter/tests/AttributeFilter.spec.tsx
src/components/filters/AttributeFilter/tests/utils.ts
stories/helper_components/AttributeFilter.tsx

Attribute filter improvements:
- new 'filter' prop which allows to define the filter including selected items
- 'title' prop for custom dropdown label
---
--- | ---
- UI SDK documentation: https://github.com/gooddata/gooddata-ui/pull/241
ONE-3999 : https://jira.intgdc.com/browse/ONE-3999

FEATURE: ONE-3999 AttributeFilter Improvements

---

package.json
yarn.lock

RELATED: BB-1690 Use correct versions of @gooddata/typings and gooddata-js

---

src/components/filters/AttributeFilter/AttributeDropdown.tsx
src/components/filters/AttributeFilter/AttributeFilter.tsx
src/components/filters/AttributeFilter/tests/AttributeDropdown.spec.tsx
src/components/filters/AttributeFilter/tests/AttributeFilter.spec.tsx

Improve handling of text filter selection. Move conversion from inner component to the AttributeFilter to improve maintainability
---
--- | ---

 BUGFIX: ONE-4067 Move conversion to the AttributeFilter and fix text element values

---

yarn.lock

FEATURE: FET-382 Update yarn.lock to use react 16.5.2

---

examples/src/components/MeasureValueFilterFormattedInPercentageExample.jsx
examples/src/components/MeasureValueFilterShownInPercentageExample.jsx
examples/src/components/MeasureValueFilterStackedToHundredPercentExample.jsx
examples/src/routes/MeasureValueFilter.jsx
examples/test/BasicComponents_test.js
examples/test/MeasureValueFilter_test.js
examples/test/utils/helpers.js

RELATED: BB-1692 Insight filtering by percentage measure value example

---

package.json
src/helpers/afmHelper.ts
src/helpers/tests/afmHelper.spec.ts
yarn.lock

RELATED: ONE-4103 Do not use filters with "Select all"

---

CHANGELOG.md
src/components/uri/Visualization.tsx

BUGFIX: ONE-4093 Use external SDK instance everywhere

---

CHANGELOG.md
src/components/uri/Visualization.tsx

Merge after patch 7.1.1 release to port bugfix to the "next-7.2.0" branch
---
--- | ---
- ONE-4112: https://jira.intgdc.com/browse/ONE-4112

RELATED: ONE-4112 Merge "master" to "next-7.2.0" branch

---

package.json
yarn.lock

RELATED: BB-1702 Upgrade mock-js with support for measure value filters

---

CHANGELOG.md
package.json
yarn.lock

RELATED: ONE-4114 Use latest numberjs package

---

package.json
yarn.lock

RELATED: FET-367 Add autofix copyright

---

package.json
styles/internal/scss/config_panel.scss
yarn.lock

RELATED: FET-387 upgrade goodstrap

---

package.json
yarn.lock

RELATED: BB-1702 Upgrade mock-js

---

package.json
src/components/filters/DateFilter/DateFilterButton/DateFilterButton.scss
src/components/filters/DateFilter/DateFilterFormWrapper/DateFilterFormWrapper.scss
src/components/filters/DateFilter/ListItem/ListItem.scss
src/components/visualizations/styles/headline.scss
yarn.lock

RELATED: ONE-4149 Rewrite goodstrap typo-mixins to be true mixins

---

stories/hoc/withAxisName.tsx

Description of changes
- Update number of charts according to real number of children to avoid timer ticks infinitely
---
--- | ---
- SD-672: https://jira.intgdc.com/browse/SD-672

BUGFIX: SD-672 Fix axis name screenshot test in react-components

---

src/components/filters/DateFilter/DateRangePicker/DateRangePicker.tsx
src/components/filters/DateFilter/utils/DateConversions.ts
src/components/filters/DateFilter/utils/Translations/DateFilterTitle.ts
src/components/filters/DateFilter/utils/Translations/tests/DateFilterTitle.spec.ts
src/components/filters/DateFilter/utils/tests/DateConversions.spec.ts
src/components/filters/DateFilter/utils/tests/OptionUtils.spec.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2556
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2380
https://jira.intgdc.com/browse/SD-688

BUGFIX: SD-688 handle convert absolute date time filter

---

src/components/core/BarChart.tsx
src/helpers/sorts.ts
src/internal/components/pluggableVisualizations/barChart/tests/PluggableBarChart.spec.tsx
src/internal/mocks/executionObjectMocks.ts
src/internal/mocks/testMocks.ts
src/internal/utils/mdObjectHelper.ts
src/internal/utils/sort.ts
src/internal/utils/tests/mdObjectHelper.spec.ts
src/internal/utils/tests/sort.spec.ts
stories/test_data/fixtures.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2549
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2373
- SD-662: https://jira.intgdc.com/browse/SD-662

BUGFIX: SD-662 Sorting in bar chart for stack by attribute

---

src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx
src/internal/components/pluggableVisualizations/headline/PluggableHeadline.tsx
src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
src/internal/utils/domHelper.ts
src/internal/utils/tests/domHelper.spec.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2571
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2374

RELATED: ONE-4029 Defensive unmount

---

src/components/filters/MeasureValueFilter/OperatorDropdownBody.tsx
src/constants/measureValueFilterOperators.ts
src/helpers/measureValueFilterOperator.ts
src/helpers/tests/measureValueFilterOperator.spec.ts
src/interfaces/MeasureValueFilter.ts
src/interfaces/tests/MeasureValueFilter.spec.ts
src/translations/en-US.json
yarn.lock

FEATURE: BB-1703 equal to & not equal to operators

---

src/internal/interfaces/Visualization.ts

RELATED: BB-1702 Extend IBucketFilter with measure value filter props

---

src/internal/components/BaseVisualization.tsx
src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx
src/internal/components/pluggableVisualizations/headline/PluggableHeadline.tsx
src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
src/internal/components/tests/BaseVisualization.spec.tsx

pass correctly onFiredDrillEvent prop to the inner components
---
--- | ---
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2398
- ONE-4034: https://jira.intgdc.com/browse/ONE-4034

RELATED: ONE-4034 Pass onFiredDrillEvent to inner component

---

src/internal/constants/uiConfig.ts
src/internal/mocks/uiConfigMocks.ts

XIRR was missing filter config which caused it to cause an error in AD.
---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2599
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2420

RELATED: RAIL-1868 add default filter config to XIRR

---

package.json
yarn.lock

Upgrade gooddata-js library with fix of AFM filters sanitization.
---
--- | ---

BUGFIX: BB-1885 Sanitize exported AFM filters

---

src/components/filters/DateFilter/DateFilterBody/DateFilterBody.tsx
src/components/filters/DateFilter/DateFilterBody/tests/DateFilterBody.spec.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2596
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2418
- SD-692: https://jira.intgdc.com/browse/SD-692

BUGFIX: SD-692 The drop-down menu of Date picker is partially hidden

---

src/components/filters/MeasureValueFilter/OperatorDropdownBody.tsx

RELATED: BB-1703 changed operators order

---

src/internal/components/pluggableVisualizations/xirr/PluggableXirr.tsx

--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2611
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2430

BUGFIX: RAIL-1928 add sanitizeUnusedFilters to XIRR

---

mock-schema.js
src/components/uri/Visualization.tsx
src/components/uri/tests/Visualization.spec.tsx
src/internal/components/configurationPanels/BaseChartConfigurationPanel.tsx
src/internal/components/configurationPanels/BubbleChartConfigurationPanel.tsx
src/internal/components/configurationPanels/HeatMapConfigurationPanel.tsx
src/internal/components/configurationPanels/ScatterPlotConfigurationPanel.tsx
src/internal/components/configurationPanels/tests/BaseChartConfigurationPanel.spec.tsx
src/internal/components/configurationPanels/tests/BubbleChartConfigurationPanel.spec.tsx
src/internal/components/configurationPanels/tests/ScatterPlotConfigurationPanel.spec.tsx
src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx
src/internal/utils/propertiesHelper.ts
src/internal/utils/tests/propertiesHelper.spec.ts

Merge [hotfix](https://github.com/gooddata/gooddata-react-components/pull/1256) to next 7.2.0 
---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2607
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2428
- SD-726: https://jira.intgdc.com/browse/SD-726

Merge release-194 to next 7.2.0

---

src/internal/components/pluggableVisualizations/xirr/tests/xirrBucketHelper.spec.ts
src/internal/components/pluggableVisualizations/xirr/xirrBucketHelper.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2623
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2438

BUGFIX: RAIL-1931  handle derived measures in XIRR

---

src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
src/internal/components/pluggableVisualizations/pivotTable/tests/PluggablePivotTable.spec.tsx

RELATED: BB-1912 fixed sort item when MVF is present

---

mock-schema.js
src/components/uri/Visualization.tsx
src/components/uri/tests/Visualization.spec.tsx
src/helpers/sorts.ts
src/internal/components/pluggableVisualizations/barChart/tests/PluggableBarChart.spec.tsx
src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx
src/internal/utils/mdObjectHelper.ts
src/internal/utils/sort.ts
src/internal/utils/tests/sort.spec.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2626
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2445
- SD-737: https://jira.intgdc.com/browse/SD-737

BUGFIX: SD-737 Put SD-662 behind FF

---

package.json
yarn.lock

RELATED: FET-395 Various fixes

---

examples/src/components/XirrExample.jsx
examples/src/routes/Xirr.jsx
examples/src/routes/_list.js
src/components/visualizations/headline/utils/calculateXirr.ts
src/components/visualizations/headline/utils/test/calculateXirr.spec.ts

Also a hidden example was added to ease verification of this
---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2641
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2451

BUGFIX: RAIL-1954 make XIRR not throw for invalid data

---

CHANGELOG.md
examples/src/components/XirrExample.jsx
examples/src/routes/Xirr.jsx
examples/src/routes/_list.js
package.json
src/components/visualizations/headline/utils/calculateXirr.ts
src/components/visualizations/headline/utils/test/calculateXirr.spec.ts
yarn.lock

Merge next-7.2.0 to develop

---

package.json
yarn.lock

BUGFIX: BB-1940 Fix exports

---

package.json
yarn.lock

RELATED: BB-1917 numberjs dependency

---

src/internal/components/pluggableVisualizations/PluggableColumnBarCharts.tsx
src/internal/components/pluggableVisualizations/areaChart/PluggableAreaChart.tsx
src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx
src/internal/components/pluggableVisualizations/bubbleChart/PluggableBubbleChart.tsx
src/internal/components/pluggableVisualizations/comboChart/PluggableComboChart.tsx
src/internal/components/pluggableVisualizations/comboChart/PluggableComboChartDeprecated.tsx
src/internal/components/pluggableVisualizations/headline/PluggableHeadline.tsx
src/internal/components/pluggableVisualizations/heatMap/PluggableHeatmap.tsx
src/internal/components/pluggableVisualizations/lineChart/PluggableLineChart.tsx
src/internal/components/pluggableVisualizations/pieChart/PluggablePieChart.tsx
src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
src/internal/components/pluggableVisualizations/pivotTable/tests/PluggablePivotTable.spec.tsx
src/internal/components/pluggableVisualizations/scatterPlot/PluggableScatterPlot.tsx
src/internal/components/pluggableVisualizations/treeMap/PluggableTreemap.tsx
src/internal/components/pluggableVisualizations/xirr/PluggableXirr.tsx
src/internal/interfaces/Visualization.ts
src/internal/interfaces/tests/Visualization.spec.ts
src/internal/mocks/referencePointMocks.ts
src/internal/utils/bucketHelper.ts
src/internal/utils/bucketRules.ts
src/internal/utils/tests/bucketConfig.spec.ts
src/internal/utils/tests/bucketHelper.spec.ts

FEATURE: BB-1844 Sanitize measure value filters on viz. switch

---

src/components/filters/MeasureValueFilter/DropdownBody.tsx
src/components/filters/MeasureValueFilter/OperatorDropdownBody.tsx
src/components/filters/MeasureValueFilter/OperatorDropdownItem.tsx
src/components/filters/MeasureValueFilter/tests/MeasureValueFilter.spec.tsx
src/translations/en-US.json
styles/scss/measureValueFilter.scss

FEATURE: BB-1712 more friendly MVF

---

examples/server/package.json
examples/server/yarn.lock

Closes #1273, closes #1274, closes #1275, closes #1276, closes #1277, closes #1278, closes #1279 
--- | ---
- gdc-analytical-designer: N/A
- gdc-dashboards: N/A

RELATED: RAIL-1975 upgrade examples/server deps

---

package.json
yarn.lock

RELATED: ONE-4237 Update goodstrap

---

mock-schema.js
src/components/core/geoChart/geoChartDataSource.ts
src/components/core/geoChart/tests/geoChartDataSource.spec.ts
src/helpers/dimensions.ts
src/helpers/tests/dimensions.spec.ts
stories/core_components/GeoPushpinChart.tsx
stories/test_data/geo_chart/geo_chart_with_location_request.json
stories/test_data/geo_chart/geo_chart_with_location_response.json
stories/test_data/geo_chart/geo_chart_with_location_result.json

…efault config.
---
--- | ---
SD-757: https://jira.intgdc.com/browse/FET-757

RELATED: SD-757 - Pushpin Chart has only location and without measure.

---

examples/src/components/ParentFilterExample.jsx

- Replace the visualization error component with a simple error label for select components. 
---
--- | ---

RELATED: FET-401 Show error label instead of visualization error

---

src/components/visualizations/chart/chartOptionsBuilder.ts

checked in the storybook that it works the same as for bar chart so that it follows the pointer only when min/max is set
---
--- | ---

BUGFIX: BB-2024 Bullet chart tooltip on min/max

---

src/components/core/GeoChart.tsx
src/components/core/geoChart/GeoChartRenderer.tsx
src/components/core/geoChart/geoChartDataLayers.ts
src/components/core/geoChart/geoChartDataSource.ts
src/components/core/geoChart/tests/GeoChartRenderer.spec.tsx
src/components/core/geoChart/tests/geoChartDataLayers.spec.ts
src/components/core/geoChart/tests/geoChartDataSource.spec.ts
src/components/core/tests/GeoChart.spec.tsx
src/constants/geoChart.ts
src/helpers/executionResultHelper.ts
src/helpers/tests/executionResultHelper.spec.ts
src/interfaces/GeoChart.ts
stories/core_components/GeoChart.tsx
stories/core_components/GeoPushpinChart.tsx
stories/data/geoChart.ts

---
--- | ---
- SD-781: https://jira.intgdc.com/browse/SD-781

FEATURE: SD-781 - Create component <GeoChartRenderer/>

---

src/components/core/GeoChart.tsx
src/components/core/geoChart/GeoChartRenderer.tsx
src/components/core/geoChart/geoChartDataSource.ts
src/components/core/geoChart/tests/GeoChartRenderer.spec.tsx
src/components/core/tests/GeoChart.spec.tsx
src/constants/geoChart.ts
src/helpers/geoChart.ts
src/helpers/tests/geoChart/geoChart.spec.ts
src/interfaces/GeoChart.ts

---
--- | ---
- SD-781: https://jira.intgdc.com/browse/SD-781

RELATED: SD-781 - Too many data points

---

src/components/core/GeoChart.tsx
src/components/core/geoChart/GeoChartLegendRenderer.tsx
src/components/core/geoChart/legends/PushpinSizeLegend.tsx
src/components/core/geoChart/legends/test/PushpinSizeLegend.spec.tsx
src/components/core/geoChart/tests/GeoChartLegendRenderer.spec.tsx
src/helpers/geoChart.ts
src/helpers/tests/geoChart/geoChart.spec.ts
stories/data/geoChart.ts
styles/scss/geoChart.scss

---
--- | ---
SD-776: https://jira.intgdc.com/browse/SD-776

FEATURE: SD-776 Legend GeoChart

---

CHANGELOG.md
package.json
yarn.lock

RELATED: BB-1907 Add MVF support for getValidElements API

---

src/components/filters/MeasureValueFilter/Dropdown.tsx

BUGFIX: BB-1956 fix alignment of MFV dropdown

---

src/components/filters/MeasureValueFilter/DropdownBody.tsx
src/components/filters/MeasureValueFilter/tests/MeasureValueFilter.spec.tsx

RELATED: BB-2046 Reset to 0% when change MVF (formatted in %) from comparison to range

---

src/translations/de-DE.json
src/translations/es-ES.json
src/translations/fr-FR.json
src/translations/ja-JP.json
src/translations/nl-NL.json
src/translations/pt-BR.json
src/translations/pt-PT.json
src/translations/zh-Hans.json

TRIVIAL: Update translations

---

examples/src/components/MeasureValueFilterDropdownExample.jsx
examples/src/components/MeasureValueFilterDropdownPercentageExample.jsx
examples/src/components/MeasureValueFilterDropdownRatioExample.jsx
examples/src/components/MeasureValueFilterExample.jsx
examples/src/components/MeasureValueFilterFormattedInPercentageExample.jsx
examples/src/components/MeasureValueFilterShownInPercentageExample.jsx
examples/src/components/MeasureValueFilterStackedToHundredPercentExample.jsx
src/components/filters/MeasureValueFilter/Dropdown.tsx
src/components/filters/MeasureValueFilter/DropdownAfmWrapper.tsx
src/components/filters/MeasureValueFilter/DropdownBody.tsx
src/components/filters/MeasureValueFilter/tests/DropdownAfmWrapper.spec.tsx
src/helpers/model/measureValueFilters.ts
src/helpers/model/tests/measureValueFilters.spec.ts
src/interfaces/MeasureValueFilter.ts
src/interfaces/tests/MeasureValueFilter.spec.ts
stories/helper_components/MeasureValueFilter.tsx

FEATURE: BB-2030 Improve interface of measure value filter dropdown

---

src/internal/utils/bucketHelper.ts

isMeasureValueFilter was not called in an if ->
it always evaluated to truthy value ->
if was always hit.
This should not change any behaviour, as a filter is either
Attribute, Date or MeasureValue for now.
---
--- | ---

TRIVIAL: add missing function call

---

package.json
yarn.lock

RELATED: BB-1713 updated goodstrap

---

package.json
yarn.lock

The caret was removed errorneously before
---
--- | ---

RELATED: RAIL-1992 add missing caret to goodstrap

---

src/components/filters/MeasureValueFilter/DropdownBody.tsx
src/components/filters/MeasureValueFilter/tests/DropdownAfmWrapper.spec.tsx
src/components/filters/MeasureValueFilter/tests/fragments/MeasureValueFilter.tsx

RELATED: BB-2069 MVF disable enter when apply is disabled

---

src/components/core/geoChart/GeoChartRenderer.tsx
src/components/core/geoChart/geoChartDataLayers.ts
src/components/core/geoChart/geoChartDataSource.ts
src/components/core/geoChart/tests/geoChartDataLayers.spec.ts
src/components/core/geoChart/tests/geoChartDataSource.spec.ts
src/constants/geoChart.ts

---
--- | ---
- SD-797: https://jira.intgdc.com/browse/SD-797

FEATURE: SD-797 - Cluster for Geo Chart

---

package.json
yarn.lock

RELATED: RAIL-1906 Update goodstrap

---

src/internal/constants/uiConfig.ts
src/internal/interfaces/Visualization.ts
src/internal/mocks/uiConfigMocks.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2707
https://jira.intgdc.com/browse/SD-783

FEATURE: SD-783 update uiConfig for display geo attribute icon

---

src/components/filters/MeasureValueFilter/DropdownBody.tsx
src/components/filters/MeasureValueFilter/tests/DropdownAfmWrapper.spec.tsx

RELATED: BB-2053 Decimals added in measure value filter dropdown

---

mock-schema.js
src/components/core/GeoChart.tsx
src/components/core/base/GeoValidatorHOC.tsx
src/components/core/base/test/GeoValidatorHOC.spec.tsx
src/constants/errorStates.ts
src/helpers/errorHandlers.ts
src/helpers/geoChart.ts
src/helpers/tests/__snapshots__/errorHandlers.spec.ts.snap
src/helpers/tests/geoChart/geoChart.spec.ts
src/translations/en-US.json

---
--- | ---
- SD-798: https://jira.intgdc.com/browse/SD-798

FEATURE: SD-798 Show no location error screen

---

src/components/visualizations/styles/tooltip.scss

BUGFIX: SD-791 fix invalid autoprefixer

---

examples/src/components/MeasureValueFilterExample.jsx
examples/src/components/MeasureValueFilterFormattedInPercentageExample.jsx
examples/src/components/MeasureValueFilterShownInPercentageExample.jsx
examples/src/components/MeasureValueFilterStackedToHundredPercentExample.jsx
examples/src/routes/_list.js
examples/test/MeasureValueFilter_test.js

FEATURE: BB-1694 Reveal MVF examples and uncomment TestCafe tests

---

styles/scss/main.scss

BUGFIX: ONE-4091 IE, Edge: Hide 2 "X" icons in search input field

---

package.json
src/components/visualizations/chart/highcharts/customConfiguration.ts
src/components/visualizations/chart/highcharts/test/customConfiguration.spec.ts
yarn.lock

RELATED: ONE-4285 Keep HC tooltip in viewport

---

examples/server/yarn.lock

Upgraded:
* set-value
* stringstream
* jsdom (because of cryptiles)
---
--- | ---
- gdc-analytical-designer: N/A only examples are changed
- gdc-dashboards: N/A only examples are changed

TRIVIAL: upgrade examples server dependencies

---

src/internal/translations/en-US.json

RELATED: SD-783 update translate for geo pushpin

---

src/components/core/geoChart/geoChartDataLayers.ts
src/components/core/geoChart/geoChartDataSource.ts
src/components/core/geoChart/tests/geoChartDataLayers.spec.ts
src/components/core/geoChart/tests/geoChartDataSource.spec.ts
styles/scss/geoChart.scss

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2791
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2552
- SD-758: https://jira.intgdc.com/browse/SD-758

RELATED: SD-758 fix hovering on center of pushpin

---

src/components/core/GeoChart.tsx
src/components/core/base/test/GeoValidatorHOC.spec.tsx
src/components/core/geoChart/GeoChartRenderer.tsx
src/components/core/tests/GeoChart.spec.tsx
src/components/tests/GeoPushpinChart.spec.tsx
src/helpers/geoChart.ts
src/helpers/tests/MdObjectHelper.spec.ts
src/helpers/tests/geoChart/geoChart.spec.ts
src/interfaces/GeoChart.ts
src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx
stories/core_components/GeoPushpinChart.tsx
stories/data/geoChart.ts
stories/uri_components/Visualization.tsx

Description of changes (if multi-commit, short global summary & context;
if single-commit, feel free to leave empty).
- propagate mapbox token from AD/KD to SDK
- refactor `mapboxAccessToken` to `mapboxToken` to sync with backend config name
---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2789 …

FEATURE: SD-815 propagate mapbox token from AD/KD to SDK

---

CHANGELOG.md

TRIVIAL: Update changelog for 7.3.0

---

examples/src/routes/MeasureValueFilter.jsx
examples/src/routes/MeasureValueFilterComponent.jsx

TRIVIAL: Copywriter review fixes for MVF examples

---

package.json
yarn.lock

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2787
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2548

RELATED: FET-429 use up-to-date goodstrap

---

examples/src/components/DrillWithExternalDataExample.jsx
examples/test/PivotTableMenu_test.js
scripts/run-testcafe.sh

- Wait for table loaded which seems tied with controls refresh.
- Mock sample data in case external service returns error.
---
--- | ---

TRIVIAL: Fix unstable exampels tests

---

src/components/core/base/GeoValidatorHOC.tsx
src/components/core/base/test/GeoValidatorHOC.spec.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2801
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2561
- SD-820: https://jira.intgdc.com/browse/SD-820

FEATURE: SD-820 prevent component update with shouldComponentUpdate

---

src/internal/components/pluggableVisualizations/pivotTable/tests/PluggablePivotTable.spec.tsx
src/internal/constants/uiConfig.ts
src/internal/interfaces/Visualization.ts
src/internal/mocks/uiConfigMocks.ts
src/internal/utils/uiConfigHelpers/tests/__snapshots__/bulletChartUiConfigHelper.spec.ts.snap

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2790
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2549
- [SD-813](https://jira.intgdc.com/browse/SD-813)

FEATURE: SD-813 Support clustering when there is location attribute only

---

src/internal/components/pluggableVisualizations/bulletChart/PluggableBulletChart.tsx

RELATED: BB-1855 fix measures distribution

---

examples/src/components/BulletChartDrillExample.jsx
examples/test/OnDrillHandlingFixtures.js
examples/test/OnDrillHandling_test.js

RELATED: BB-2001 Fix Bullet chart TestCafe test

---

src/internal/components/pluggableVisualizations/bulletChart/PluggableBulletChart.tsx
src/internal/components/pluggableVisualizations/bulletChart/tests/PluggableBulletChart.spec.tsx

RELATED: BB-1855 measures distribution fix

---

src/components/visualizations/utils/drilldownEventing.ts
src/components/visualizations/utils/test/drilldownEventing.spec.tsx

BUGFIX: BB-2120 Target measure y value when drilling on attribute element

---

src/internal/utils/uiConfigHelpers/bulletChartUiConfigHelper.ts

BUGFIX: BB-2122 primary measure missing error fix

---

examples/test/MeasureValueFilter_test.js

FEATURE: BB-2096 Enable TestCafe test

---

src/internal/components/configurationPanels/BulletChartConfigurationPanel.tsx
src/internal/components/configurationPanels/tests/BulletChartConfigurationPanel.spec.tsx
src/internal/components/pluggableVisualizations/bulletChart/PluggableBulletChart.tsx
src/internal/components/pluggableVisualizations/bulletChart/tests/PluggableBulletChart.spec.tsx

BUGFIX: BB-2127 bullet chart configuration fixes

---

src/components/core/geoChart/GeoChartRenderer.tsx
src/components/core/geoChart/tests/GeoChartRenderer.spec.tsx
src/interfaces/GeoChart.ts
src/internal/interfaces/Visualization.ts
styles/scss/geoChart.scss

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2844
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2588
- SD-821: https://jira.intgdc.com/browse/SD-821

FEATURE: SD-821 Handle Geo chart in PDF export

---

examples/test/PivotTableDynamic_test.js
examples/test/PivotTableSizing_test.js
examples/test/PivotTable_test.js
src/components/core/PivotTable.tsx

FEATURE: ONE-4310 Auto resize behaviour on table resize

---

src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2863

RELATED: SD-817 apply bounds instead of center if it's not existing

---

src/components/core/base/GeoValidatorHOC.tsx
src/components/core/base/test/GeoValidatorHOC.spec.tsx
src/components/tests/mocks.tsx
src/execution/fixtures/ExecuteAfm.fixtures.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2857
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2599
- SD-857: https://jira.intgdc.com/browse/SD-857

FEATURE: SD-857 Handle filter for Geo chart on KD

---

src/constants/geoChart.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2862
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2600
- SD-855: https://jira.intgdc.com/browse/SD-855

FEATURE: SD-855 Disable infinite geochart scrolling

---

src/components/visualizations/utils/drilldownEventing.ts
src/components/visualizations/utils/test/drilldownEventing.spec.tsx

BUGFIX: BB-2123 Add measure type to bullet chart attribute drilling

---

src/components/filters/AttributeFilter/AttributeDropdown.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2864
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2601

BUGFIX: RAIL-2139 Fix Attribute Filter Component checkbox issue, RAIL-2084 Fix Attribute Filter loading issue

---

README.md
examples/src/components/GeoPushpinChartClusteringExample.jsx
examples/src/components/GeoPushpinChartConfigurationExample.jsx
examples/src/components/GeoPushpinChartWithCategoryLegendExample.jsx
examples/src/components/GeoPushpinChartWithColorLegendExample.jsx
examples/src/components/VisualizationGeoPushpinChartByIdentifierExample.jsx
examples/src/components/VisualizationGeoPushpinChartByUriExample.jsx
examples/src/routes/BasicComponents.jsx
examples/src/routes/GeoPushpinChartDemo.jsx
examples/src/routes/VisualizationByIdentifier.jsx
examples/src/routes/VisualizationByUri.jsx
examples/src/routes/_list.js
examples/src/utils/fixtures.js
examples/src/utils/fixturesGeoChart.js
examples/test/BasicComponents_test.js
examples/test/GeoPushpinChart_test.js
examples/test/VisualizationByIdentifier_test.js
examples/test/VisualizationByUri_test.js
examples/webpack.config.js
scripts/ci-deploy-and-testcafe.sh

---
--- | ---
SD-761: https://jira.intgdc.com/browse/SD-761

FEATURE: SD-761 GeoChart Example

---

src/components/visualizations/chart/events/setupDrilldownToParentAttribute.ts
src/components/visualizations/chart/events/test/setupDrilldownToParentAttribute.spec.ts

BUGFIX: BB-2152 Bullet chart parent attribute drilling with null value

---

src/components/core/geoChart/geoChartTooltip.ts
src/components/core/geoChart/tests/geoChartTooltip.spec.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2869
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2605
- SD-853: https://jira.intgdc.com/browse/SD-853

BUGFIX: SD-853 Ignore color format in measures

---

src/internal/components/pluggableVisualizations/bulletChart/PluggableBulletChart.tsx
src/internal/components/pluggableVisualizations/bulletChart/tests/PluggableBulletChart.spec.tsx
src/internal/constants/uiConfig.ts
src/internal/mocks/referencePointMocks.ts
src/internal/utils/bucketConfig.ts
src/internal/utils/uiConfigHelpers/bulletChartUiConfigHelper.ts
src/internal/utils/uiConfigHelpers/tests/__snapshots__/bulletChartUiConfigHelper.spec.ts.snap
src/internal/utils/uiConfigHelpers/tests/bulletChartUiConfigHelper.spec.ts

FEATURE: BB-2057 Bullet chart support overtime comparison

---

examples/src/components/utils/ExampleWithExport.jsx
examples/src/components/utils/SourceDropdown.jsx
examples/src/routes/Export.jsx

FEATURE: RAIL-2140 Include ExampleWithExport code on live examples page

---

src/internal/components/configurationPanels/GeoPushpinConfigurationPanel.tsx
src/internal/components/configurationPanels/tests/GeoPushpinConfigurationPanel.spec.tsx
src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx
src/internal/constants/supportedProperties.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2879
https://jira.intgdc.com/browse/SD-861
https://jira.intgdc.com/browse/SD-876

BUGFIX: SD-861 SD-876 update supported properties and remove handle center/zoom on AD

---

examples/src/components/BulletChartExample.jsx
examples/src/components/VisualizationBulletByIdentifierExample.jsx
examples/src/components/VisualizationBulletByUriExample.jsx
examples/src/routes/BasicComponents.jsx
examples/src/routes/VisualizationByIdentifier.jsx
examples/src/routes/VisualizationByUri.jsx
examples/src/routes/_list.js
examples/src/utils/fixtures.js

FEATURE: BB-1949 Bullet chart documentation

---

README.md

FEATURE: GD-44265 Deprecation of old versions of GDC UI SDK

---

src/internal/constants/bucket.ts
src/internal/constants/uiConfig.ts
src/internal/mocks/uiConfigMocks.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2870
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2608
- SD-867: https://jira.intgdc.com/browse/SD-867

BUGFIX: SD-867 only support geo/location DF on Location bucket

---

src/components/visualizations/chart/chartOptions/bulletChartOptions.ts
src/components/visualizations/chart/chartOptions/test/bulletChartOptions.spec.ts
src/components/visualizations/styles/charts.scss

when target value is null
---
--- | ---

BUGFIX: BB-2158 bullet chart fails to render

---

src/components/core/geoChart/geoChartTooltip.ts
src/components/core/geoChart/tests/geoChartTooltip.spec.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2888
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2623
- SD-879: https://jira.intgdc.com/browse/SD-879

BUGFIX: SD-879 Show wrong measure format on the tooltip

---

src/components/core/geoChart/GeoChartRenderer.tsx
src/constants/geoChart.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2904
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2637
https://jira.intgdc.com/browse/SD-881
https://jira.intgdc.com/browse/SD-882

BUGFIX: SD-881 SD-882 handle interaction event on map

---

CHANGELOG.md

TRIVIAL: Update changelog for 7.4.0

---

src/components/visualizations/styles/bulletChart.scss
styles/internal/scss/bullet_chart.scss
styles/scss/bulletChart.scss
styles/scss/main.scss

BUGFIX: BB-2132 Fix bullet chart zero width target bars

---

src/internal/translations/en-US.json

BUGFIX: ONE-4338 Change the description in legend position settings

---

package.json
yarn.lock

RELATED: BB-2033 Upgrade goodstrap

---

package.json
src/components/filters/AttributeFilter/AttributeDropdown.tsx
src/components/filters/AttributeFilter/AttributeFilter.tsx
src/components/filters/AttributeFilter/AttributeLoader.tsx
src/components/filters/AttributeFilter/model.ts
src/components/filters/AttributeFilter/tests/AttributeDropdown.spec.tsx
src/components/filters/AttributeFilter/tests/AttributeFilter.spec.tsx
src/components/filters/AttributeFilter/tests/AttributeLoader.spec.tsx
src/components/filters/AttributeFilter/tests/utils.ts
styles/scss/main.scss
yarn.lock

--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2872
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2612

BUGFIX: RAIL-2021 Fix Attribute Filter dropdown button title, BUGFIX: RAIL-2085 Fix Attribute Filter icon render issue

---

src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx
src/internal/components/pluggableVisualizations/geoChart/tests/PluggableGeoPushpinChart.spec.tsx
src/internal/components/pluggableVisualizations/heatMap/PluggableHeatmap.tsx
src/internal/components/pluggableVisualizations/heatMap/tests/PluggableHeatmap.spec.tsx
src/internal/mocks/referencePointMocks.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2922
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2648
- SD-863: https://jira.intgdc.com/browse/SD-863
- SD-865: https://jira.intgdc.com/browse/SD-865

BUGFIX: SD-863 SD-865 fix switching geo chart

---

src/components/core/geoChart/GeoChartRenderer.tsx

---
--- | ---
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2651
https://jira.intgdc.com/browse/SD-881

RELATED: SD-881 handle remove navigator control

---

examples/src/routes/MeasureValueFilter.jsx
src/internal/components/configurationPanels/BulletChartConfigurationPanel.tsx
src/internal/components/configurationPanels/tests/BulletChartConfigurationPanel.spec.tsx

BUGFIX: BB-2153 Bullet y axis name configuration

---

package.json
src/components/filters/MeasureValueFilter/Dropdown.tsx
src/components/filters/MeasureValueFilter/DropdownAfmWrapper.tsx
src/components/filters/MeasureValueFilter/DropdownBody.tsx
src/components/filters/MeasureValueFilter/TreatNullValuesAsZeroCheckbox.tsx
src/components/filters/MeasureValueFilter/tests/DropdownAfmWrapper.spec.tsx
src/components/filters/MeasureValueFilter/tests/fragments/MeasureValueFilter.tsx
src/helpers/model/measureValueFilters.ts
src/interfaces/MeasureValueFilter.ts
src/translations/en-US.json
stories/helper_components/MeasureValueFilter.tsx
styles/scss/measureValueFilter.scss
yarn.lock

checkbox in measure value filter dropdown
---
--- | ---

RELATED: BB-2141 treat null values as zero

---

package.json
src/components/filters/AttributeFilter/AttributeDropdown.tsx
src/components/filters/AttributeFilter/AttributeFilter.tsx
yarn.lock

--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2955
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2669

BUGFIX: RAIL-2163, RAIL-2070 Fix AttributeFilter render issue on mobile

---

package.json
yarn.lock

RELATED: BB-2141 Upgrade mock-js

---

.github/CODEOWNERS

TRIVIAL: PBR as watcher of translations

---

src/components/core/geoChart/GeoChartRenderer.tsx
src/interfaces/GeoChart.ts
src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx
stories/core_components/GeoPushpinChart.tsx

TRIVIAL: fix typo grammar

---

src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2954
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2667
https://jira.intgdc.com/browse/SD-861

BUGFIX: SD-861 handle undo/redo for geo chart

---

src/components/core/geoChart/GeoChartRenderer.tsx
src/helpers/geoChart/common.ts
src/helpers/tests/geoChart/common.spec.ts
src/internal/components/configurationControls/PushpinSizeControl.tsx
src/internal/components/configurationPanels/GeoPushpinConfigurationPanel.tsx
src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx

Clone `supportedControls` before passing it down to child components
--- 
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2947
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2663
- SD-899: https://jira.intgdc.com/browse/SD-899

BUGFIX: SD-899 fix pins re-rendered

---

examples/server/package.json
examples/server/yarn.lock

TRIVIAL: upgrade example server dependencies

---

src/translations/en-US.json

for treat null as zero checkbox
---
--- | ---

TRIVIAL: BB-2141 changed label and tooltip text

---

src/components/core/geoChart/GeoChartRenderer.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2972
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2686
https://jira.intgdc.com/browse/SD-906

BUGFIX: SD-906 only remove zoom button if it's existed

---

package.json
yarn.lock

RELATED: CAT-1 use up-to-date goodstrap

---

src/helpers/model/tests/__snapshots__/measureValueFilters.spec.ts.snap
src/helpers/model/tests/measureValueFilters.spec.ts

RELATED: BB-2141 Add missing unit tests, convert to snapshots

---

package.json
yarn.lock

RELATED: CAT-1 Use the last version of goodstrap

---

styles/scss/measureValueFilter.scss

TRIVIAL: Align MVF tooltip question mark with label

---

src/internal/components/configurationControls/tests/PushpinSizeControl.spec.tsx
src/internal/components/configurationPanels/GeoPushpinConfigurationPanel.tsx
src/internal/components/pluggableVisualizations/lineChart/PluggableLineChart.tsx
src/internal/components/pluggableVisualizations/lineChart/tests/PluggableLineChart.spec.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2992
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2707
- SD-902: https://jira.intgdc.com/browse/SD-902

BUGFIX: SD-902 fix transform geo attribute on line chart

---

src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx
src/internal/components/pluggableVisualizations/geoChart/tests/PluggableGeoPushpinChart.spec.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2991
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2706
- SD-901: https://jira.intgdc.com/browse/SD-901

BUGFIX: SD-901 fix switch to geo chart with derived and arithmetic measures

---

package.json
yarn.lock

---
--- | ---
ONE-4417: https://jira.intgdc.com/browse/ONE-4417

RELATED: ONE-4417 ONE-3399 Upgrade goodstrap

---

examples/src/components/MeasureValueFilterComponentExample.jsx
examples/src/components/MeasureValueFilterComponentPercentageExample.jsx
examples/src/components/MeasureValueFilterComponentRatioExample.jsx
examples/src/components/MeasureValueFilterDropdownComponentExample.jsx
src/components/filters/MeasureValueFilter/MeasureValueFilter.tsx
src/components/filters/MeasureValueFilter/MeasureValueFilterDropdown.tsx
src/components/filters/MeasureValueFilter/typings.ts

RELATED: BB-2150 optional onCancel prop

---

package.json
yarn.lock

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/2996
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2715

RELATED: SD-849 release dep

---

src/internal/components/pluggableVisualizations/bulletChart/PluggableBulletChart.tsx
src/internal/components/pluggableVisualizations/bulletChart/bucketHelper.ts
src/internal/components/pluggableVisualizations/bulletChart/tests/PluggableBulletChart.spec.tsx
src/internal/components/pluggableVisualizations/bulletChart/tests/bucketHelper.spec.ts
src/internal/mocks/referencePointMocks.ts

BUGFIX: BB-2176 bullet bucket items distribution

---

examples/src/components/GeoPushpinChartConfigurationPointsGroupNearbyExample.jsx
examples/src/components/GeoPushpinChartConfigurationPointsSizeExample.jsx
examples/src/routes/GeoPushpinChartDemo.jsx
examples/test/GeoPushpinChart_test.js

---
--- | ---
SD-761: https://jira.intgdc.com/browse/SD-761

FEATURE: SD-761 add example for Points Configuration

---

package.json
yarn.lock

---
--- | ---
- gdc-analytical-designer: N/A no change in code
- gdc-dashboards: N/A no change in code

RELATED: FET-435 upgrade stylelint-config

---

src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx
src/internal/components/pluggableVisualizations/geoChart/tests/PluggableGeoPushpinChart.spec.tsx
src/internal/mocks/referencePointMocks.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3002
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2719
- SD-918: https://jira.intgdc.com/browse/SD-918

BUGFIX: SD-918 fix duplication geo attribute on location and segment by buckets

---

.storybook/test-storybook-canvas.config.js
examples/src/components/GeoPushpinChartDrillExample.jsx
examples/src/routes/OnDrillHandling.jsx
src/components/core/base/GeoValidatorHOC.tsx
src/components/core/base/test/GeoValidatorHOC.spec.tsx
src/components/core/geoChart/GeoChartInner.tsx
src/components/core/geoChart/GeoChartRenderer.tsx
src/components/core/geoChart/geoChartDataSource.ts
src/components/core/geoChart/geoChartTooltip.ts
src/components/core/geoChart/tests/GeoChartInner.spec.tsx
src/components/core/geoChart/tests/geoChartDataSource.spec.ts
src/components/core/geoChart/tests/mock.ts
src/components/visualizations/utils/drilldownEventing.ts
src/components/visualizations/utils/test/drilldownEventing.spec.tsx
src/constants/visualizationTypes.ts
src/helpers/executionResultHelper.ts
src/helpers/geoChart/colorStrategy.ts
src/helpers/geoChart/data.ts
src/helpers/geoChart/executionResultHelper.ts
src/helpers/tests/geoChart/executionResultHelper.spec.ts
src/interfaces/DrillEvents.ts
stories/core_components/GeoPushpinChart.tsx
stories/data/geoChart.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3000
- https://client-demo.na.intgdc.com:50017/analyze/
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2713
- https://client-demo.na.intgdc.com:50025/dashboards/
- SD-903: https://jira.intgdc.com/browse/SD-903

FEATURES: SD-903 Support drilling in KD on geo chart

---

src/components/core/base/test/GeoValidatorHOC.spec.tsx
src/components/core/geoChart/GeoChartOptionsWrapper.tsx
src/components/core/geoChart/geoChartColor.ts
src/components/core/geoChart/tests/GeoChartOptionsWrapper.spec.tsx
src/components/core/geoChart/tests/geoChartColor.spec.ts
src/constants/geoChart.ts
src/translations/en-US.json

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3009
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2729
SD-919: https://jira.intgdc.com/browse/SD-919
SD-869: https://jira.intgdc.com/browse/SD-869

BUGFIX: SD-919 SD-869

---

package.json
yarn.lock

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3014
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2735

REALTED: FET-451, RAIL-2236, FET-462 Update goodstrap dependences

---

package.json
yarn.lock

RELATED: ONE-4353 Upgrade mock-js

---

examples/test/AttributeFilter_test.js
examples/test/BasicComponents_test.js
examples/test/ChartConfiguration_test.js
examples/test/ComboChart_test.js
examples/test/DateFilter_test.js
examples/test/DatePicker_test.js
examples/test/DrillWithExternalData_test.js
examples/test/DynamicMeasures_test.js
examples/test/Execute_test.js
examples/test/GeoPushpinChart_test.js
examples/test/GlobalFilter_test.js
examples/test/MeasureValueFilter_test.js
examples/test/OnDrillHandling_test.js
examples/test/ParentFilter_test.js
examples/test/PivotTableDemo_test.js
examples/test/PivotTableDrillExample_test.js
examples/test/PivotTableDynamic_test.js
examples/test/PivotTableMenu_test.js
examples/test/PivotTableSizing_test.js
examples/test/PivotTable_test.js
examples/test/ResponsiveChart_test.js
examples/test/Sorting_test.js
examples/test/VisualizationByIdentifier_test.js
examples/test/VisualizationByUri_test.js
examples/test/utils/helpers.js
examples/test/utils/userRole.js

RELATED: FET-388 Improve Authentication logic in examples testcafe tests.

---

src/components/filters/DateFilter/DateFilterBody/DateFilterBody.scss
src/components/filters/DateFilter/DateFilterBody/DateFilterBody.tsx
src/components/filters/DateFilter/ExcludeCurrentPeriodToggle/ExcludeCurrentPeriodToggle.scss
src/components/filters/DateFilter/ExcludeCurrentPeriodToggle/ExcludeCurrentPeriodToggle.tsx
src/components/filters/DateFilter/ListItem/ListItem.scss
src/components/filters/DateFilter/Select/VirtualizedSelectMenu.tsx
src/components/uri/Visualization.tsx
styles/scss/dateFilter.scss

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3033
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2749

BUGFIX: RAIL-1869 Fix Date Filter styling issues and cross-compability issues, RAIL-2233 Fix Visualization rendering after login failed

---

src/components/filters/DateFilter/DateFilterBody/DateFilterBody.scss

RELATED: RAIL-1869 Adjust dropdown body on mobile view

---

src/internal/components/pluggableVisualizations/bulletChart/bucketHelper.ts
src/internal/components/pluggableVisualizations/bulletChart/tests/bucketHelper.spec.ts
src/internal/components/pluggableVisualizations/scatterPlot/PluggableScatterPlot.tsx
src/internal/components/pluggableVisualizations/scatterPlot/tests/PluggableScatterPlot.spec.tsx
src/internal/mocks/referencePointMocks.ts
src/internal/utils/bucketHelper.ts
src/internal/utils/tests/bucketHelper.spec.ts

BUGFIX: BB-2176 measures placement

---

src/components/uri/Visualization.tsx

RELATED: RAIL-2233 Fix Visualization component caching to clear on error

---

src/helpers/sorts.ts
src/helpers/tests/sorts.spec.ts
src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx
src/internal/utils/sort.ts
src/internal/utils/tests/sort.spec.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3032
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2748
SD-921: https://jira.intgdc.com/browse/SD-921

BUGFIX: SD-921 Sorting legend items by alphabet order

---

examples/test/Export_test.js
examples/test/utils/exportUtils.js

TEST: QA-10123 Automation test cover export insight in UI SDK to XLSX, CSV

---

src/components/filters/DateFilter/RelativeRangePicker/RelativeRangePicker.tsx

BUGFIX: RAIL-1575 Fix Date Filter floating range highlight

---

examples/test/Export_test.js
examples/test/utils/exportUtils.js

TRIVIAL: QA-10123 Refactor authorise logic

---

src/components/filters/DateFilter/DateFilterBody/DateFilterBody.scss
src/components/filters/DateFilter/DateFilterBody/DateFilterBody.tsx
src/components/filters/DateFilter/ExcludeCurrentPeriodToggle/ExcludeCurrentPeriodToggle.scss
src/components/filters/DateFilter/ExcludeCurrentPeriodToggle/ExcludeCurrentPeriodToggle.tsx
src/components/filters/DateFilter/ListItem/ListItem.scss
src/components/filters/DateFilter/Select/VirtualizedSelectMenu.tsx
src/components/uri/Visualization.tsx
styles/scss/dateFilter.scss

RELATED: RAIL-2233, RAIL-1869 Merge significant changes that should be part of RC-7.5.0 release

---

CHANGELOG.md

---
--- | ---
- SD-933: https://jira.intgdc.com/browse/SD-933

RELATED: SD-933 Update changelog for 7.5.0

---

CHANGELOG.md

RELATED: SD-933 Add missing feature to changelog for 7.5.0

---

package.json
yarn.lock

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3050
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2768

RELATED: RAIL-2107 use up-to-date goodstrap

---

src/internal/components/pluggableVisualizations/areaChart/PluggableAreaChart.tsx
src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx
src/internal/components/pluggableVisualizations/bubbleChart/PluggableBubbleChart.tsx
src/internal/components/pluggableVisualizations/bulletChart/PluggableBulletChart.tsx
src/internal/components/pluggableVisualizations/comboChart/PluggableComboChart.tsx
src/internal/components/pluggableVisualizations/comboChart/PluggableComboChartDeprecated.tsx
src/internal/components/pluggableVisualizations/headline/PluggableHeadline.tsx
src/internal/components/pluggableVisualizations/headline/tests/PluggableHeadline.spec.tsx
src/internal/components/pluggableVisualizations/heatMap/PluggableHeatmap.tsx
src/internal/components/pluggableVisualizations/lineChart/PluggableLineChart.tsx
src/internal/components/pluggableVisualizations/pieChart/PluggablePieChart.tsx
src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
src/internal/components/pluggableVisualizations/scatterPlot/PluggableScatterPlot.tsx
src/internal/components/pluggableVisualizations/treeMap/PluggableTreemap.tsx
src/internal/mocks/referencePointMocks.ts
src/internal/utils/bucketConfig.ts
src/internal/utils/bucketRules.ts
src/internal/utils/tests/bucketConfig.spec.ts
src/internal/utils/tests/bucketRules.spec.ts
src/internal/utils/uiConfigHelpers/baseChartUiConfigHelper.ts

BUGFIX: BB-2280 Week sliced insight does not support derived bucket items

---

src/components/core/pivotTable/agGridDataSourceUtils.ts
src/components/core/pivotTable/tests/agGridDataSourceUtils.spec.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3057
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2777

RELATED: ONE-4434 Fix caching to avoid duplicates

---

CHANGELOG.md

FEATURE: SD-933 mark 7.5.0 deprecated, release 7.6.0

---

.storybook/test-storybook-canvas.config.js
__mocks__/fixtures.ts
mock-schema.js
src/components/uri/Visualization.tsx
src/helpers/MdObjectHelper.ts
src/helpers/geoChart/common.ts
src/helpers/tests/MdObjectHelper.spec.ts
stories/uri_components/Visualization.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3072
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2783
- SD-868: https://jira.intgdc.com/browse/SD-868
- SD-939: https://jira.intgdc.com/browse/SD-939

BUGFIX: SD-868 SD-939 Visualization geo chart display Location in the tooltip

---

src/components/visualizations/chart/legend/StaticLegend.tsx
styles/scss/geoChart.scss

---
--- | ---
-   [x] Squash commits 
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3077
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2789
- SD-945: https://jira.intgdc.com/browse/SD-945

BUGFIX: SD-945 The paging number of the legend works incorrectly

---

examples/src/index.jsx

BUGFIX: SD-953 trivial change to rebuild GD examples on master

---

examples/src/components/PivotTableColumnsGrowToFitExample.jsx
examples/src/components/PivotTableSizingWithGrowToFitExample.jsx
src/components/core/PivotTable.tsx
src/components/core/tests/PivotTable.spec.tsx
src/interfaces/PivotTable.ts
src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
stories/core_components/PivotTable.tsx

BUGFIX: ONE-4456 Move growToFit to columnSizing

---

src/components/core/PivotTable.tsx
src/components/core/tests/PivotTable.spec.tsx

BUGFIX: BB-2092 Show custom LoadingComponent in PivotTable

---

package.json
yarn.lock

BUGFIX: BB-2286 Override incorrect Show in % formats in saved insights

---

src/components/core/geoChart/GeoChartRenderer.tsx
src/constants/geoChart.ts

---
--- | ---
- gdc-analytical-designer: [PR](https://github.com/gooddata/gdc-analytical-designer/pull/3093), [client-demo](https://client-demo.na.intgdc.com:50018/analyze/)
- gdc-dashboards: [PR](https://github.com/gooddata/gdc-dashboards/pull/2796), [client-demo](https://client-demo.na.intgdc.com:50020/dashboards/)
- SD-932: https://jira.intgdc.com/browse/SD-932

BUGFIX: SD-932 Fix attribution position

---

.github/CODEOWNERS

Update codeowners
---
--- | ---

TRIVIAL: Update codeowners

---

src/components/core/PivotTable.tsx
src/components/core/tests/PivotTable.spec.tsx

BUGFIX: BB-2290 Disable LoadingComponent in PivotTable

---

examples/src/components/MeasureValueFilterChartConfiguration.jsx
examples/src/components/VisualizationMeasureValueFilterByIdentifierExample.jsx
examples/src/routes/VisualizationByIdentifier.jsx
examples/src/routes/_list.js
examples/src/utils/fixtures.js
examples/test/MeasureValueFilterComponent_test.js
examples/test/MeasureValueFilter_test.js
examples/test/VisualizationByIdentifier_test.js

TEST: QA-10884 Automation test cover Value filters in GD.UI (R2)

---

CHANGELOG.md
src/components/core/base/hook/TranslationsHook.ts
src/components/core/geoChart/GeoChartInner.tsx
src/components/core/geoChart/GeoChartLegendRenderer.tsx
src/components/core/geoChart/tests/GeoChartLegendRenderer.spec.tsx

---
--- | ---
- SD-960: https://jira.intgdc.com/browse/SD-960

BUGFIX: SD-960 remove hooks which can not work with react version 16.5.2

---

src/components/core/pivotTable/AggregationsMenu.tsx
src/components/core/pivotTable/tests/AggregationsMenu.spec.tsx

BUGFIX: BB-1581 Close AggregationsMenu on scroll

---

examples/src/index.jsx

BUGFIX: BB-1578 Fix live examples width

---

src/components/visualizations/utils/drilldownEventing.ts
src/components/visualizations/utils/test/drilldownEventing.spec.tsx
src/helpers/geoChart/executionResultHelper.ts
src/helpers/tests/geoChart/executionResultHelper.spec.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3113
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2829
- SD-965: https://jira.intgdc.com/browse/SD-965

BUGFIX: SD-965 Selected location is not transferred using drill to dashboard

---

src/components/core/geoChart/GeoChartInner.tsx
src/components/core/geoChart/GeoChartOptionsWrapper.tsx
src/components/core/geoChart/geoChartDataLayers.ts
src/components/core/geoChart/geoChartDataSource.ts
src/components/core/geoChart/legends/test/PushpinCategoryLegend.spec.tsx
src/components/core/geoChart/tests/GeoChartInner.spec.tsx
src/components/core/geoChart/tests/GeoChartLegendRenderer.spec.tsx
src/components/core/geoChart/tests/GeoChartOptionsWrapper.spec.tsx
src/components/core/geoChart/tests/geoChartDataLayers.spec.ts
src/helpers/geoChart/data.ts
src/helpers/tests/geoChart/data.spec.ts
src/interfaces/GeoChart.ts

Root cause:
- Masked attribute items have same masking value (eg `Undisclosed`) which is not accepted by mapbox filter.
Solution:
- Replace attribute value/name to its uri which is more unique
---
--- | ---
- gdc-analytical-designer: [PR](https://github.com/gooddata/gdc-analytical-designer/pull/3112), [client-demo](https://client-demo.na.intgdc.com:50033/analyze/)
- …

BUGFIX: SD-926 add Mapbox filter by using attribute uri

---

src/components/core/PivotTable.tsx

Consider also failed data pages as loaded so autoresizing can be done
---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3127
- ONE-4453: https://jira.intgdc.com/browse/ONE-4453

BUGFIX: ONE-4453 Consider also failed pages as done

---

src/components/core/geoChart/geoChartTooltip.ts
src/components/core/geoChart/legends/PushpinSizeLegend.tsx
src/components/core/geoChart/tests/geoChartTooltip.spec.ts
src/components/visualizations/chart/highcharts/customConfiguration.ts
src/components/visualizations/chart/tooltip.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3122
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2838
SD-826: https://jira.intgdc.com/browse/SD-826
SD-862: https://jira.intgdc.com/browse/SD-862

BUGFIX: SD-826 SD-862 fixed layout tooltip

---

examples/src/components/SamePeriodBarChartExample.jsx
examples/src/components/SamePeriodBulletChartExample.jsx
examples/src/components/SamePeriodComboChartExample.jsx
examples/src/components/SamePeriodHeadLineExample.jsx
examples/src/components/SamePeriodLineChartExample.jsx
examples/src/components/SamePeriodPivotTableExample.jsx
examples/src/routes/TimeOverTimeComparison.jsx
examples/test/TimeOverTimeComparison_test.js
examples/test/utils/config.js

TEST: QA-10967 Cover missing cases for PoP in Testcafe

---

examples/src/components/PivotTableSizingComplexExample.jsx
examples/src/routes/PivotTableSizing.jsx
examples/test/PivotTableSizingReset_test.js
examples/test/utils/pivotTableHelpers.js

RELATED: ONE-4408 Reset manual width by doubleclick on Resizer

---

examples/src/components/MeasureValueFilterAndAttributeFilter.jsx
examples/src/components/MeasureValueFilterAndDateFilter.jsx
examples/src/components/MeasureValueFilterAndDateFilterAndAttributeFilter.jsx
examples/src/routes/_list.js
examples/test/MeasureValueFilter_test.js

TEST: QA-10970 Extend tests for filters combination

---

examples/src/routes/ArithmeticMeasure.jsx
examples/test/ArithmericMeasures_test.js

TEST: QA-10968 Automation test for AM Measures in Testcafe

---

CHANGELOG.md

TRIVIAL: Fix changelog typo

---

examples/test/BasicComponents_test.js

TEST: QA-8729 Donut Chart

---

examples/test/BasicComponents_test.js

TEST:QA-8731 Bubble Chart

---

examples/src/components/DynamicSortingExample.jsx
examples/src/routes/PivotTableDemo.jsx
examples/test/PivotTableDemo_test.js
examples/test/Sorting_test.js
examples/test/VisualizationByUri_test.js

TEST: QA-10976 Add missing tests for Sorting

---

examples/src/components/StackedAreaChartExample.jsx
examples/test/BasicComponents_test.js

TEST: QA-8733 Stacked Area Chart

---

examples/test/BasicComponents_test.js

TEST: QA-8732 Scatter plot chart

---

src/translations/de-DE.json
src/translations/es-ES.json
src/translations/fr-FR.json
src/translations/ja-JP.json
src/translations/nl-NL.json
src/translations/pt-BR.json
src/translations/pt-PT.json
src/translations/zh-Hans.json

TRIVIAL: Localizations update

---

examples/test/BasicComponents_test.js

TEST: QA-8730 Heatmap

---

src/components/core/PivotTable.tsx
src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
src/internal/components/pluggableVisualizations/pivotTable/tests/PluggablePivotTable.spec.tsx
src/internal/components/pluggableVisualizations/pivotTable/tests/widthItemsHelpers.spec.ts
src/internal/components/pluggableVisualizations/pivotTable/tests/widthItemsMock.ts
src/internal/components/pluggableVisualizations/pivotTable/widthItemsHelpers.ts
src/internal/components/pluggableVisualizations/xirr/PluggableXirr.tsx
src/internal/constants/supportedProperties.ts
src/internal/mocks/referencePointMocks.ts
src/internal/utils/propertiesHelper.ts
src/internal/utils/tests/propertiesHelper.spec.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3119
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2870

FEATURE: ONE-4405 Manual column resizing

---

docker/.config
gdc_fossa.yaml

FEATURE: FET-478 Add FOSSA configuration

---

src/internal/components/pluggableVisualizations/geoChart/PluggableGeoPushpinChart.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3161
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2880
- SD-942: https://jira.intgdc.com/browse/SD-942

RELATED: SD-942 fix save button enabled

---

src/components/core/PivotTable.tsx
src/components/core/pivotTable/agGridUtils.ts
src/components/core/pivotTable/tests/agGridUtils.spec.ts

BUGFIX: ONE-4508 Sanitize fingerprint from dataSource in PivotTable

---

mock-schema.js
src/components/uri/Visualization.tsx

Reflect final structure of properties. Use getProperties helper everywhere
---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3172
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2890
- ONE-4507: https://jira.intgdc.com/browse/ONE-4507

BUGFIX: ONE-4507 Fix the path to the columnWidths in properties

---

src/components/core/base/VisualizationLoadingHOC.tsx
src/components/core/base/test/VisualizationLoadingHOC.spec.tsx
src/index.ts
src/interfaces/PushData.ts

RELATED: BB-2349 drill to attribute url

---

src/components/core/pivotTable/ResizedColumnsStore.ts
src/components/core/pivotTable/tests/ResizedColumnsStore.spec.ts

BUGFIX: ONE-4514 Missing validator for allMeasureColumnWidthItem

---

src/internal/components/pluggableVisualizations/pivotTable/tests/widthItemsHelpers.spec.ts
src/internal/components/pluggableVisualizations/pivotTable/tests/widthItemsMock.ts
src/internal/components/pluggableVisualizations/pivotTable/widthItemsHelpers.ts

BUGFIX: ONE-4515 Manual width of all columns with metaKey is not persisted

---

package.json
yarn.lock

RELATED: RAIL-2395, RAIL-2441 Upgrade goodstrap dependency

---

src/components/simple/SyntaxHighlightingInput.tsx
src/components/simple/tests/SyntaxHighlightingInput.spec.tsx
src/interfaces/DrillEvents.ts

RELATED: BB-2328 SyntaxHighlightingInput callback to report cursor position

---

src/constants/geoChart.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3188
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2904
- SD-994: https://jira.intgdc.com/browse/SD-994

FEATURE: SD-994 Increase pin limit in GeoChart to 25k

---

package.json
yarn.lock

RELATAED: CAT-131 bumb goodstrap version

---

src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
src/internal/components/pluggableVisualizations/pivotTable/tests/PluggablePivotTable.spec.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3179
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2901

RELATED: ONE-4489 update properties references

---

src/components/core/geoChart/GeoChartRenderer.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3239
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2964
- SD-1014: https://jira.intgdc.com/browse/SD-1014

BUGFIX: SD-1014 Geo chart doesn't render pins in the exported file when export to PDF

---

package.json
yarn.lock

RELATED: FET-484 Upgrade copyright-fix script

---

src/components/core/PivotTable.tsx
src/components/core/tests/PivotTable.spec.tsx

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3225
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2948
- SD-995: https://jira.intgdc.com/browse/SD-995

BUGFIX: SD-995 Fix PDF exporting for PivotTable

---

.github/CODEOWNERS

TRIVIAL: Remove PJA from codeowners of translations

---

package.json
yarn.lock

BUGFIX: ONE-4422 Roll to selected dashboard

---

__mocks__/fixtures.ts
examples/test/OnDrillHandlingFixtures.js
src/components/uri/Visualization.tsx
src/helpers/measureTitleHelper.ts
src/helpers/tests/measureTitleHelper.spec.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3267
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/2973
- SD-1012: https://jira.intgdc.com/browse/SD-1012

BUGFIX: SD-1012 Metric name in KPI wasn't updated after it had been changed in Manage page

---

src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx

BUGFIX: ONE-4570 Manual width isn't respected

---

package.json
yarn.lock

RELATED: CAT-19 Bump Goodstrap

---

package.json
yarn.lock

RELATED: BB-2423 upgrade goodstrap and gooddata-js

---

src/components/visualizations/chart/HighChartsRenderer.tsx
src/components/visualizations/chart/legend/legendBuilder.ts
src/components/visualizations/chart/test/HighChartsRenderer.spec.tsx
src/constants/MediaQueries.ts
src/internal/components/BaseVisualization.tsx
src/internal/components/pluggableVisualizations/baseChart/PluggableBaseChart.tsx
src/internal/components/pluggableVisualizations/baseChart/tests/PluggableBaseChart.spec.tsx

RELATED: ONE-4467 Fix legend in KD

---

.storybook/test-storybook.config.js
stories/core_components/AreaChart.tsx
stories/core_components/ComboChart.tsx

Instead of test specific selectors modify the default one to work with readyWrapper
---
--- | ---
- FET-469: https://jira.intgdc.com/browse/FET-469

FEATURE: FET-469 Unify default selector to work with readyWrapper

---

package.json
yarn.lock

RELATED: FET-474 Upgrade gooddata-js

---

__mocks__/fixtures.ts
src/helpers/measureTitleHelper.ts
src/helpers/tests/measureTitleHelper.spec.ts

---
--- | ---
- gdc-analytical-designer: https://github.com/gooddata/gdc-analytical-designer/pull/3334
- gdc-dashboards: https://github.com/gooddata/gdc-dashboards/pull/3093
SD-1045: https://jira.intgdc.com/browse/SD-1045

BUGFIX: SD-1045 Metric name is shown as localIdentifier in KD if insight has local date filter

---

src/internal/translations/es-ES.json
stories/core_components/GeoPushpinChart.tsx

TRIVIAL: Update localizations

---

package.json
yarn.lock

RELATED: FET-458 Update gooddata-js

---

package.json
yarn.lock

RELATED: FET-458 Update packages with vulnerabilities

---

src/components/core/geoChart/GeoChartRenderer.tsx

RELATED: FET-434 Remove all scss imports

---

CHANGELOG.md

RELATED: RAIL-2725 update changelog for SDK8

---

README.md

RELATED: RAIL-2782 update supported versions in README

---

CHANGELOG.md

RELATED: RAIL-2812 Add 7.9.0 changelog entry

---

src/components/filters/DateFilter/DateFilterButton/DateFilterButton.scss
src/components/filters/DateFilter/DateRangePicker/DateRangePicker.scss
src/components/visualizations/chart/test/Chart.spec.tsx
src/components/visualizations/styles/table.scss
src/components/visualizations/table/totals/utils.ts
src/helpers/executionResultHelper.ts
src/helpers/featureFlags.ts
styles/scss/pivotTable.scss

RELATED: FET-564 Fix sonar-reported issues in legacy FE repositories

---

.sonar.settings

RELATED: FET-564 Sonar config

---

examples/test/utils/config.js
scripts/ci-deploy-and-testcafe.sh

Examples proxy no longer use authenticated user, removing config params
---
--- | ---

RELATED: RAIL-3301 Remove unused username/password param 

---

package.json
src/internal/components/pluggableVisualizations/pivotTable/PluggablePivotTable.tsx
src/internal/utils/colors.ts
yarn.lock

This solves the security alert for that version.
Also cherry-picks several dependabot commits (to save time compared to merging each one by itself).
---
--- | ---

RELATED: RAIL-710 remove immer dependency, bump others

---

examples/src/components/utils/Login.jsx
examples/src/components/utils/Registration.jsx
package.json
yarn.lock

RELATED: FET-733 Upgrade yup

---

NOTICES.txt
package.json

RELATED: LR-542 add NOTICES, fix licence metadata

---

package.json

RELATED: FET-1147 Remove heroku postbuild script and add info

---

sonar-project.properties

Migration from on-prem sonarqube to sonarcloud (public) instances.
---
--- | ---

INFRA-176: Add sonar-project.properties - cfg file for sonarcloud
